### ISSUE TITLE
ippfind: add LOC record checking and filtering

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#1]
It would be useful to add support for querying for the presence of published LOC records and filtering results based on proximity based on data from LOC records.  

IPP Everywhere (5100.14) requires Printers to publish LOC records, but we are currently lacking a tool that would allow the PWG IPP Everywhere Self Certification test suite to validate whether the device has published a LOC record for its IPP services.

**Comment by michaelrsweet** [comment]
Tracking in upstream project:

    https://github.com/apple/cups/issues/4834

I'll keep this one open until the first is merged over.

**Comment by michaelrsweet** [comment]
The parent bug was closed a long time ago - see details...
