### ISSUE TITLE
Cannot compile on Raspbian (on Raspberry Pi 3) with MuPDF from Git sources

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#10]
I'm trying to compile on a Raspberry Pi 3 with Raspbian (with all updates as of today).

In place of MuPDF I used the checked out Git sources (from *git://git.ghostscript.com/mupdf.git*) as of today.

Not sure if I SHOULD use an officially released source tarball?

Anyway, I'm now seeing this error:

<pre>
Making all in cups...
Making all in proxy...
Making all in server...
Making all in tools...
Compiling ipptransform.c...
ipptransform.c: In function ‘xform_document’:
ipptransform.c:2081:12: error: too few arguments to function ‘fz_new_pixmap’
   pixmap = fz_new_pixmap(context, cs, (int)ras.header.cupsWidth, (int)ras.band_height);
            ^
In file included from /usr/local/include/mupdf/fitz.h:35:0,
                 from ipptransform.c:26:
/usr/local/include/mupdf/fitz/pixmap.h:51:12: note: declared here
 fz_pixmap *fz_new_pixmap(fz_context *ctx, fz_colorspace *cs, int w, int h, int alpha);
            ^
ipptransform.c:2086:40: error: passing argument 2 of ‘fz_new_draw_device’ from incompatible pointer type [-Werror]
   device = fz_new_draw_device(context, pixmap);
                                        ^
In file included from /usr/local/include/mupdf/fitz.h:46:0,
                 from ipptransform.c:26:
/usr/local/include/mupdf/fitz/device.h:344:12: note: expected ‘const struct fz_matrix *’ but argument is of type ‘struct fz_pixmap *’
 fz_device *fz_new_draw_device(fz_context *ctx, const fz_matrix *transform, fz_pixmap *dest);
            ^
ipptransform.c:2086:12: error: too few arguments to function ‘fz_new_draw_device’
   device = fz_new_draw_device(context, pixmap);
            ^
In file included from /usr/local/include/mupdf/fitz.h:46:0,
                 from ipptransform.c:26:
/usr/local/include/mupdf/fitz/device.h:344:12: note: declared here
 fz_device *fz_new_draw_device(fz_context *ctx, const fz_matrix *transform, fz_pixmap *dest);
            ^
ipptransform.c: At top level:
cc1: error: unrecognized command line option "-Wno-tautological-compare" [-Werror]
cc1: all warnings being treated as errors
../Makedefs:138: recipe for target 'ipptransform.o' failed
make[1]: *** [ipptransform.o] Error 1
Makefile:30: recipe for target 'all' failed
make: *** [all] Error 1
</pre>

**Comment by michaelrsweet** [comment]
The Git sources are really a pre-release version of 2.0, which is not source compatible... Stick with 1.9a for now until they update the version number that I can detect...
