### ISSUE TITLE
Small issues/typos in man pages

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#11]
I see a few small issues in man pages:

**man ippserver:**

* command line parameter *`-c command`* should start on a line of its own.
* command line parameter *`−f type/subtype,[...]* should start on a line of its own.

**man ippproxy:**

* The *Conforming to* section, still says *"The ippproxy program is unique to CUPS"*.

**man ipptransform:**

* The initial *Name* section contains a typo: "ipptran***a***form".
* In the *Options* section the following options should be starting as a new item each:
    1. *`−o "name=value[...name=value]"`*
    1. *`−r resolution[,...,resolution]`*
    1. *`−s {flipped|manual-tumble|normal|rotated} `*
    1. *`−t type[,...,type] `*
    1. *`−v `*

**Comment by michaelrsweet** [comment]
[master 8147d5a] Fix some more typos (Issue #11)

The ipptransform changes were already done...

**Comment by KurtPfeifle** [comment]
Funny, strange...

If I run `man doc/ipptransform.man` in the Git source directory, the typo is gone.

If I run `make -n install`, it tells me where it installs the man pages and which ones:

```
Installing in doc...
/Users/kp/svn-git-stuff/git.ippsample/install-sh -d -m 755 /usr/local/share/man/man1
for file in  ipptool.man ; do \
		man="`basename $file .man`.1"; \
		/Users/kp/svn-git-stuff/git.ippsample/install-sh -c -m 444 $file /usr/local/share/man/man1/$man; \
	done
/Users/kp/svn-git-stuff/git.ippsample/install-sh -d -m 755 /usr/local/share/man/man5
for file in ipptoolfile.man; do \
		man="`basename $file .man`.5"; \
		/Users/kp/svn-git-stuff/git.ippsample/install-sh -c -m 444 $file /usr/local/share/man/man5/$man; \
	done
/Users/kp/svn-git-stuff/git.ippsample/install-sh -d -m 755 /usr/local/share/man/man8
for file in ippproxy.man ippserver.man; do \
		man="`basename $file .man`.8"; \
		/Users/kp/svn-git-stuff/git.ippsample/install-sh -c -m 444 $file /usr/local/share/man/man8/$man; \
	done
```

So installation of `ipptransform.man` seems not to happen.

If I run `sudo make install` I see this output:

```
Installing in doc...
```

If I look into the `Makefile`, it contains 

```
install:
    for dir in $(DIRS) doc; do \
        echo Installing in $$dir...; \
        (cd $$dir; $(MAKE) $(MFLAGS) install) || exit 1; \
    done
```

If I run `man /usr/local/share/man/man1/ipptransform.1` I still see the typo, and the file date is June 16th.

If I look into `doc/Makefile`, I see an inconsistency in how the manpages are named: some are via referred to with variables, some are with their real names:

```
MAN1		=	\
			$(IPPFIND_MAN) \
			ipptool.man \
			$(IPPTRANSFORM_MAN)
```

**Comment by michaelrsweet** [comment]
Run configure again - the man pages are now conditionally installed,
