### ISSUE TITLE
ipptool: the '-d' option seems to be broken

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#117]
Running with latest origin/master (af178264fab5d20040005192232993e2fbf2beee), the -d option appears to be broken. When I provide it on the command line, like so:

$ ippfind -N 'AirPrintPDF' -x ipptool -vt '{}' -d 'DOCFORMAT=application/pdf' -f test_file.pdf create-job.test \;

The value of DOCFORMAT isn't updated by the -d option. If I call the one installed in /usr/bin on my macOS 10.13.3 laptop (/usr/bin/ipptool --version returns "CUPS v2.2.5") the -d option works as expected. Attached the "create-job.test" file I was using.

[create-job.test.txt](https://github.com/istopwg/ippsample/files/1799107/create-job.test.txt)

**Comment by michaelrsweet** [comment]
It's a bug in the new combined parser.

[master 1a3df8d] Fix DEFINE-DEFAULT (Issue #117)
