### ISSUE TITLE
ipptool: Add support for variables specifying date strings in a few formats

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#118]
It would be valuable in some cases to be able to have ipptool provide date values in a few different formats to a .test file in execution. A few different variables could be defined to allow a small amount of selection to be made:

- $date-string : Long form human readable date string (e.g. when "date" is run on a UNIX system with no arguments)
- $date-code : Date code such as "20180319" or "2018-03-19" for March 19, 2018
- $date-code-long : Longer date code with minutes and seconds level resolution e.g. "20180319145232" or "2018-03-19-14-52-32" for March 19, 2018 2:52:32 PM

I'm not picky about the formats really, but some are useful for generating unique file names while others are better for logging / human reading. But the format should be consistent with [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) so that machine systems consuming the strings can parse them properly.

**Comment by michaelrsweet** [comment]
The problem with fuzzy date/time parsing is that it a) is English-centric and b) fails in unpredictable ways. For example, I am an American living in Canada. In the US, the short form of a date is mm/dd/yy. But in Canada the short form is dd/mm/yy. That is one of the reasons for the ISO date/time format, which is what we currently use when parsing and displaying dateTime values.

What specific use cases do you see having fuzzy date parsing to be helpful?

I can see supporting relative values like "tomorrow at 3pm", "next week", etc. or an equivalent locale-neutral format like "+daysT+hours:minutes:seconds" and "+daysThh:mm:ss". We could also adopt the ISO 8601 time interval format - "PnYnMnWnDTnHnMnS" (number years, months, weeks, days, hours, minutes, and seconds) and "PnYnMnWnDThh:mm:ss[.mmm]" (date interval at a specific time).

**Comment by wifiprintguy** [comment]
Mostly I wanted the current system date / time available as a variable in the execution of a test file.

On Mar 19, 2018, at 5:06 PM, Michael R Sweet <notifications@github.com<mailto:notifications@github.com>> wrote:


The problem with fuzzy date/time parsing is that it a) is English-centric and b) fails in unpredictable ways. For example, I am an American living in Canada. In the US, the short form of a date is mm/dd/yy. But in Canada the short form is dd/mm/yy. That is one of the reasons for the ISO date/time format, which is what we currently use when parsing and displaying dateTime values.

What specific use cases do you see having fuzzy date parsing to be helpful?

I can see supporting relative values like "tomorrow at 3pm", "next week", etc. or an equivalent locale-neutral format like "+daysT+hours:minutes:seconds" and "+daysThh:mm:ss". We could also adopt the ISO 8601 time interval format - "PnYnMnWnDTnHnMnS" (number years, months, weeks, days, hours, minutes, and seconds) and "PnYnMnWnDThh:mm:ss[.mmm]" (date interval at a specific time).

**Comment by michaelrsweet** [comment]
OK, then it sounds supporting ISO 8601 time intervals might do the trick. Can you maybe provide a snippet of a test file showing how you'd use the current date/time value so we can make sure that use case is properly supported?

Thanks!

**Comment by wifiprintguy** [comment]
I should have provided that originally. 😊 Here's an example:

```
{
    NAME "->->-> Create-Job to make a Job <-<-<-"
    OPERATION Create-Job
    GROUP operation-attributes-tag
    ATTR charset attributes-charset utf-8
    ATTR naturalLanguage attributes-natural-language en
    ATTR uri printer-uri $uri
    ATTR name requesting-user-name $user
    ATTR name job-name "Cancel My Jobs Test Job $datecodelong"
    ATTR boolean ipp-attribute-fidelity false
    
    STATUS successful-ok
    STATUS server-error-job-canceled
    STATUS server-error-busy REPEAT-MATCH REPEAT-LIMIT 30

    EXPECT job-uri OF-TYPE uri COUNT 1 IN-GROUP job-attributes-tag WITH-VALUE "$IPP_URI_SCHEME"
    EXPECT job-id OF-TYPE integer COUNT 1 IN-GROUP job-attributes-tag WITH-VALUE >0
    EXPECT job-id DEFINE-VALUE CLOSE_JOB_TEST_JOB_1_ID
    EXPECT ?job-uuid
    EXPECT job-state OF-TYPE unknown|enum COUNT 1 IN-GROUP job-attributes-tag WITH-VALUE 3,4,5,6
    EXPECT ?job-state-message OF-TYPE text IN-GROUP job-attributes-tag
    EXPECT job-state-reasons OF-TYPE keyword IN-GROUP job-attributes-tag
}

```

**Comment by michaelrsweet** [comment]
OK, so I think there are two asks:

1. Define a variable that is populated with the current date and time at the start of the run, let's call it "$datetime". Thus, "$datetime" will always return the same value throughout a test.
2. Add support for relative dateTime values in attributes, using the ISO 8601 format. This will allow for sending things like the "job-hold-until-time" Job Template attribute with a time interval.

Does that sound about right to you?

**Comment by wifiprintguy** [comment]
> OK, so I think there are two asks:
> 
> 1. Define a variable that is populated with the current date and time at the start of the run, let's call it "$datetime". Thus, "$datetime" will always return the same value throughout a test.

I'd prefer if it was given the current value whenever it is referenced, instead of being statically set at execution time, because I could achieve that today by putting this in my .test file:

DEFINE-DEFAULT datetime 197001010000

and then set it at execution time like so:

`$ ipptool -vt 'ipp://my-printer.local./ipp/print' -d datetime=$(date +"%Y%m%d%H%M") datetest.test`

But I won't be picky. 😊 

> 2. Add support for relative dateTime values in attributes, using the ISO 8601 format. This will allow for sending things like the "job-hold-until-time" Job Template attribute with a time interval.

That sounds good too but isn't what I was thinking about.

**Comment by michaelrsweet** [comment]
Well, perhaps we do both - "$start-date" and "$current-date", along with the relative 8601 forms for attributes.

**Comment by michaelrsweet** [comment]
OK, I opted to use "$date-current" and "$date-start" for the variable names.
