### ISSUE TITLE
ippserver: fix support for "1setOf octetString" attributes where the attribute value has spaces embedded within

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#119]
I am trying to configure ippserver to present a custom "printer-input-trays" attribute that would provide the following set of strings:

name=Tray 1;type=sheetFeedManual;mediafeed=-2;mediaxfeed=-2;maxcapacity=100;level=0;status=9;
name=Tray 2;type=sheetFeedAutoNonRemovableTray;mediafeed=170000;mediaxfeed=110000;maxcapacity=250;level=-3;status=0;
name=auto;type=other;mediafeed=85000;mediaxfeed=110000;maxcapacity=500;level=-3;status=0;

The ippserver configuration file syntax should be something like this:

`ATTR octetString        printer-input-tray name=Tray 1;type=sheetFeedManual;mediafeed=-2;mediaxfeed=-2;maxcapacity=100;level=0;status=9;,name=Tray 2;type=sheetFeedAutoNonRemovableTray;mediafeed=170000;mediaxfeed=110000;maxcapacity=250;level=-3;status=0;,name=auto;type=other;mediafeed=85000;mediaxfeed=110000;maxcapacity=500;level=-3;status=0;`

Unfortunately, ippserver is unhappy with the spaces in the values for the "name" key. I have tried wrapping the separate strings in double quotes with the commas outside, like this:

`ATTR octetString        printer-input-tray "name=Tray 1;type=sheetFeedManual;mediafeed=-2;mediaxfeed=-2;maxcapacity=100;level=0;status=9;","name=Tray 2;type=sheetFeedAutoNonRemovableTray;mediafeed=170000;mediaxfeed=110000;maxcapacity=250;level=-3;status=0;","name=auto;type=other;mediafeed=85000;mediaxfeed=110000;maxcapacity=500;level=-3;status=0;"`

Unfortunately, that didn't work. Neither did escaping the spaces with a backslash. I tried wrapping the entire set of strings in double quotes, but that resulted in there being only one big long octetString to be generated (confirmed this in Wireshark).

I don't know if this is a code fix or a documentation fix or both, but creating a set of strings where one or more of the strings in the set has white space within is awkward to describe in an ippserver .conf file.

**Comment by michaelrsweet** [comment]
Hmm, I'm going to create a Github project corresponding to the GSoC 2018 project and add this one to the bin - quotes *should* work but obviously that isn't the case... :/

**Comment by wifiprintguy** [comment]
Tried with both single and double quotes, both resulted in an error line to be written like so:

Unknown directive "," on line 55 of "./print/test-printer-input-tray.conf".

**Comment by michaelrsweet** [comment]
This appears to be fixed now...
