### ISSUE TITLE
ippsample on Windows

### ISSUE THREAD

**Issue by daryl-williams** [istopwg/ippsample#12]
Hi Michael, Not sure if your interested but I was able to build ippsample on Windows 10 using the cygwin development environment, much to my surprise ;) I had to make some minor changes, mostly casts and a #define _GNU_SOURCE for a missing (non posix i guess) asprintf function.

It also appears to be running just fine, although I still have to run some tests.

Regards,

Daryl

**Comment by michaelrsweet** [comment]
We do intend for the sample code to run on Windows (as much as is possible given its limitations) and there is a Visual Studio project (that I admit have not updated in a while) for building the sample code.

Supporting Visual Studio builds is our primary focus - Cygwin is an interesting approach but if we don't produce native applications using the Microsoft tools then we have "failed" as far as the project is concerned...

If you can send a diff (or a pull request) containing your changes to make it compile with Cygwin, I'll see about merging them.

Thanks!

**Comment by daryl-williams** [comment]
Hi Michael, You will find attached the the diffs I made to compile 
ippsample using cygwin.



On 7/5/16 5:24 AM, Michael R Sweet wrote:
>
> We do intend for the sample code to run on Windows (as much as is 
> possible given its limitations) and there is a Visual Studio project 
> (that I admit have not updated in a while) for building the sample code.
>
> Supporting Visual Studio builds is our primary focus - Cygwin is an 
> interesting approach but if we don't produce native applications using 
> the Microsoft tools then we have "failed" as far as the project is 
> concerned...
>
> If you can send a diff (or a pull request) containing your changes to 
> make it compile with Cygwin, I'll see about merging them.
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/istopwg/ippsample/issues/12#issuecomment-230463523>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AA_wdaQiNpUcmuFsf-45Y-ysxwwU31q2ks5qSkzvgaJpZM4JCrqW>.
>


diff --git a/cups/debug.c b/cups/debug.c
index a25e4b1..0e6b2db 100644
--- a/cups/debug.c
+++ b/cups/debug.c
@@ -109,7 +109,7 @@ _cups_debug_printf(const char *format,	/* I - Printf-style format string */
   * Filter as needed...
   */
 
-  if (isdigit(format[0]))
+  if (isdigit((unsigned char)format[0]))
     level = *format++ - '0';
   else
     level = 0;
@@ -192,7 +192,7 @@ _cups_debug_puts(const char *s)		/* I - String to output */
   * Filter as needed...
   */
 
-  if (isdigit(s[0]))
+  if (isdigit((unsigned char)s[0]))
     level = *s++ - '0';
   else
     level = 0;
diff --git a/cups/http-addrlist.c b/cups/http-addrlist.c
index a8237eb..7335cb2 100644
--- a/cups/http-addrlist.c
+++ b/cups/http-addrlist.c
@@ -757,7 +757,7 @@ httpAddrGetList(const char *hostname,	/* I - Hostname, IP address, or NULL for p
     else if (isdigit(*service & 255))
       portnum = atoi(service);
     else if ((port = getservbyname(service, NULL)) != NULL)
-      portnum = ntohs(port->s_port);
+      portnum = ntohs((uint16_t)port->s_port);
     else if (!strcmp(service, "http"))
       portnum = 80;
     else if (!strcmp(service, "https"))
diff --git a/cups/http-support.c b/cups/http-support.c
index 2af4814..ae7c844 100644
--- a/cups/http-support.c
+++ b/cups/http-support.c
@@ -2030,14 +2030,14 @@ http_copy_decode(char       *dst,	/* O - Destination buffer */
 	  */
 
           src ++;
-	  if (isalpha(*src))
-	    quoted = (tolower(*src) - 'a' + 10) << 4;
+	  if (isalpha((unsigned char)*src))
+	    quoted = (tolower((unsigned char)*src) - 'a' + 10) << 4;
 	  else
 	    quoted = (*src - '0') << 4;
 
           src ++;
-	  if (isalpha(*src))
-	    quoted |= tolower(*src) - 'a' + 10;
+	  if (isalpha((unsigned char)*src))
+	    quoted |= tolower((unsigned char)*src) - 'a' + 10;
 	  else
 	    quoted |= *src - '0';
 
diff --git a/cups/language.c b/cups/language.c
index f1afecc..88a6e36 100644
--- a/cups/language.c
+++ b/cups/language.c
@@ -1601,11 +1601,11 @@ cups_unquote(char       *d,		/* O - Unquoted string */
     if (*s == '\\')
     {
       s ++;
-      if (isdigit(*s))
+      if (isdigit((unsigned char)*s))
       {
 	*d = 0;
 
-	while (isdigit(*s))
+	while (isdigit((unsigned char)*s))
 	{
 	  *d = *d * 8 + *s - '0';
 	  s ++;
diff --git a/server/ippserver.h b/server/ippserver.h
index 03ac18e..32ba6e1 100644
--- a/server/ippserver.h
+++ b/server/ippserver.h
@@ -19,7 +19,7 @@
 
 #define _IPP_PRIVATE_STRUCTURES 0	/* Disable private IPP stuff */
 #define _CUPS_NO_DEPRECATED 1		/* Disable deprecated stuff */
-
+#define _GNU_SOURCE  		        /* Work around for missing asprintf function */
 
 /*
  * Include necessary headers...
