### ISSUE TITLE
Support binary (hex) values

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/ippsample#122]
It would be nice to support specification of arbitrary binary (hex) values, particularly for octetString attributes. Syntax should look like:

    <pairs-of-hex-digits>

For example, a string of bytes from 0 to 7 would look like:

    <0001020304050607>

For readability, whitespace should be allowed between pairs, e.g.:

    <000102030405060708090a0b0c0d0e0f
     101112131415161718191a1b1c1d1e1f
    ...
     f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff>

**Comment by wifiprintguy** [comment]
Can this value type be listed with other values, or must it be the only value token? Like for instance what should the parser do if the file has a value that is a mixture of a string and a hex token

    ATTR name job-name "Hybrid Job Name - "<4950502045766572797768657265e284a2>

Would it parse that to produce the string value "Hybrid Job Name - IPP Everywhere™" ?
