### ISSUE TITLE
ippserver: the -P option adds "job-password-supported" but is missing "job-password-encryption-supported"

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#13]
The definition of "job-password-encryption-supported" in PWG 5100.11 section 10.4 says this:

'If the operation attribute "job-password" is supported, then this attribute MUST be supported.'

Yet if ippserver is provided with the "-P" option, it will implement "job-password-supported" but not "job-password-encryption-supported".

This can be remedied by defining "job-password-encryption-supported" and redefining "job-password-supported" in a config file or via the command line.  But it really ought to do it properly and list "job-password-encryption-supported" with value "none" if no encryption is supported by ippserver.

**Comment by michaelrsweet** [comment]
Well, the current code doesn't really do anything with job-password, but yes we should populate job-password-encryption-supported anyways.

**Comment by michaelrsweet** [comment]
[master e4d569f] Include job-password-encryption-supported attribute (Issue #13)
