### ISSUE TITLE
ippserver: doesn't support the "note" DNS-SD TXT record key

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#136]
It could be setting the value based on the "printer-location" attribute (RFC 8011), or at least setting it to "" if printer-location is absent, but specifying "printer-location" in the .conf file does not result in the "note" key/value being listed in the TXT record.

**Comment by michaelrsweet** [comment]
[master e204a60] Fix DNS-SD kind and note keys (Issue #135, Issue #136)
