### ISSUE TITLE
DNS-SD TXT record: Color=T only if pages-per-minute-color is set

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#137]
In the DNS-SD TXT record, ippserver will only set Color=T if pages-per-minute-color is set in the .conf file or the "-s" argument is given to ippserver. This seems a little odd since "pages-per-minute" and "pages-per-minute-color" are RECOMMENDED but not REQUIRED, and having "color-supported" = 'true' fails to set Color=T.

Not a major issue but might want to switch on both of those things...

**Comment by michaelrsweet** [comment]
Easy enough to pull from the color-supported attribute instead.

**Comment by michaelrsweet** [comment]
[master 7754e0b] Look at color-supported for Color key in TXT record (Issue #137)
