### ISSUE TITLE
job-creation-attributes-supported not listing "output-bin" even when "output-bin-supported" is listed in .conf file

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#138]
When I put this in my .conf file:

```
ATTR keyword            output-bin-supported                      face-down
ATTR keyword            output-bin-default                        face-down
```
I might have expected ippserver to somehow divine that that attribute should be listed by "job-creation-attributes-supported". Or I could manually create my "job-creation-attributes-supported". It wasn't automagically added, but I'm not sure if there is a practical way for ippserver to be clairvoyant about which attributes it ought to automatically list in "job-creation-attributes-supported".

**Comment by michaelrsweet** [comment]
Yeah, right now you just need to override the default job-creation-attributes-supported value. And perhaps we should always list output-bin and provide default values (face-down?) for output-bin-default and output-bin-supported?

**Comment by michaelrsweet** [comment]
[master f7de097] Missing output-bin from job-creation-attributes-supported (Issue #138)
