### ISSUE TITLE
ippserver: The "-2" option is ignored in some cases when the  "-C" option is specified

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#14]
If I run ippserver like so:

./ippserver -vv -2 "foo"

the output will show this, among other things:

[Printer foo] sides-default (keyword) one-sided
[Printer foo] sides-supported (1setOf keyword) one-sided,two-sided-long-edge,two-sided-short-edge

But if I have it load a set of configuration files (system.conf, print/foo.conf) from the local directory, and run ippserver like so:

./ippserver -vv -2 -C .

the output will show this:

[Printer foo] sides-default (keyword) one-sided
[Printer foo] sides-supported (keyword) one-sided

I can override this by specifying "side-default" and "sides-supported" in print/foo.conf but I don't think I should have to if I have provided the "-2" option.

(Similarly, I might have expected the "-2" option to make "two-sided-long-edge" the value for "sides-default"...)

**Comment by michaelrsweet** [comment]
The command-line options are only provided for creating a single print queue; they don't set defaults for the queues defined.

I'll use this bug to track adding an error if both the single-queue and config directory options are specified.

**Comment by michaelrsweet** [comment]
[master 1a94175] Don't allow config dir and printer options at the same time (Issue #14)
