### ISSUE TITLE
Add example PDF file that is just a vector graphic

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/ippsample#145]
We need a purely graphic PDF test file included with the example files.

**Comment by wifiprintguy** [comment]
How about the attached (created with inkscape)?
[test-file-pwg-vector.pdf](https://github.com/istopwg/ippsample/files/2186522/test-file-pwg-vector.pdf)

**Comment by michaelrsweet** [comment]
We don’t want to include text since the point is to have a file to use with print-content-optimize=graphics

**Comment by michaelrsweet** [comment]
I've pushed an initial vector test file; might try to find an existing SVG file and convert that to PDF as well...

**Comment by michaelrsweet** [comment]
OK, I added a different PDF I made with MuPDF - right now hairline graphics at different angles and some gradients for CMYK primaries.
