### ISSUE TITLE
ippserver: IPP "printer-uuid" value / DNS-SD TXT record "UUID" key value change after every run

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#15]
Some clients encode the value of the IPP "printer-uuid" value / DNS-SD TXT record "UUID" key value into the URI.  Unfortunately, "ippserver" changes the printer's UUID after every run, which means the queue becomes invalid on some client systems (tested with OS X 10.11.6).

Moreover, if I have specified a UUID in a Printer configuration file, I see the value set early in the stream of output, but then it is overwritten later in the logging reported by ippserver.  Early in the logging, where attribute definitions are read from the config file, I will see this:

[Printer foo] printer-uuid (uri) urn:uuid:0d3d8dbd-bcd1-dead-beef-76c7e04caf42
....
[Printer foo] printer-uuid (uri) urn:uuid:5accac29-2942-3a10-5367-7a4d46ec0701

and it is this second one that will be used by ippserver. That prevents me from specifying a durable UUID for the Printer.

[foo.conf.txt](https://github.com/istopwg/ippsample/files/452902/foo.conf.txt)

**Comment by michaelrsweet** [comment]
[master 0895036] Fix printer-uuid handling (Issue #15)
