### ISSUE TITLE
pwg-raster-document-type-supported value

### ISSUE THREAD

**Issue by deepak0405** [istopwg/ippsample#156]
I used ipptool and get-printer-attributes to get attribute values for ippserver and remote cups queue. The "pwg-raster-document-type-supported" attribute's for remote cups queue contains values containing  '-'  (eg srgb-8)  whereas for ippserver, the value contains  '_' for eg: srgb-8. Which one is the correct format?

**Comment by wifiprintguy** [comment]
The PWG Raster format is specified by PWG 5102.4. Section 9.3 lists the keywords to be registered in the IANA IPP Registry (https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml) and those registered match those listed in 5102.4. The keywords are of the form:
    <label>_<BitsPerPixel>

Examples:

- adobe-rgb_8
- adobe-rgb_16
- cmyk_8
- device1_8
- device7_16
- rgb_16
- sgray_1
- sgray_8
- srgb_16

Given this and your description above, the ippserver implementation seems to be correct, while CUPS is incorrect. (Which version of CUPS?)

**Comment by deepak0405** [comment]
I am using cups 2.2.2. I am also attaching the output of get-printer-attributes.
[file_printer_ipp.txt](https://github.com/istopwg/ippsample/files/2267653/file_printer_ipp.txt)

**Comment by michaelrsweet** [comment]
I see duplicate attributes here but the CUPS source in Github only adds a single attributes with black_1, sgray_8, and srgb_8 as the possible values.

What operating system/Linux distribution are you using?

**Comment by deepak0405** [comment]
I am using ubuntu 17.04.

**Comment by michaelrsweet** [comment]
OK, I'm guessing this is being cause by Ubuntu changes to the base CUPS sources. Please file a bug with the Ubuntu folks...
