### ISSUE TITLE
Broken internal-links on page  https://istopwg.github.io/ippsample/ subpages like ippserver, ipptool 

### ISSUE THREAD

**Issue by JackGrinningCat** [istopwg/ippsample#157]
Hi

I was going through the github.io site, and found that links are partly wrong. 
They point all to sites with the prefixes "man-" within the generated pages.
But the pages are all without "man-" on the server.

- [ ] ippfind - See also section - link to [ipptool](https://istopwg.github.io/ippsample/man-ipptool.html?TOPIC=Man+Pages) is broken. without man- [ipptool](https://istopwg.github.io/ippsample/ipptool.html?TOPIC=Man+Pages) is working

Every site below the ippsample page(besides API overview which only got page internal links)  has those errors. So it seems to be a general error while generating those pages.

Some further examples:
- [ ] ippproxy - Description Section - link to [ippserver ](https://istopwg.github.io/ippsample/man-ippserver.html?TOPIC=Man+Pages) is broken
- [ ] ippserver - Print Service Configuration Files - links to ipptoolfile and ipptransform broken

I would like to send a pull request, but I don't have any insight to the tools or which pages are used for that documentation, so it is easier to bring this minor issues to your attention than further diving into the creation process

**Comment by JackGrinningCat** [comment]
I don't know but mantohtml.c seems to do the job but I think the pages need a recreation, but my trials with the tool missed to create links. :-|

**Comment by wifiprintguy** [comment]
Perhaps we ought to consider publishing out of the "/docs directory" rather than a "gh-pages" branch? 

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by wifiprintguy** [comment]
The logic in mantohtml.c to generate local links seems to be a no-op. I'll get the pages fixed manually, and we should probably look at switching to the /docs folder for serving content rather than the branch, which is neglected and will need manual intervention to stay up-to-date.

**Comment by michaelrsweet** [comment]
Smith, we don't want the web site published from the master branch because it will always be ahead of any released software we provide.

**Comment by wifiprintguy** [comment]
That's fine, though we don't currently provide ippsample binary releases. We need to fix some of our tools (mantohtml) to reduce the human touches needed to regenerate this content in the future. One pull request coming on that.

@JackGrinningCat , thanks for flagging this up. I think all the man pages are now "working" correctly. Closing this for now - if you notice problems, re-open or create a new issue.
