### ISSUE TITLE
Add an example of an ATTR declaration for a collection to the ipptoolfile or ippserver man page

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#16]
It isn't very obvious how one would encode, for instance, "media-col-ready" in an ATTR declaration, because of the nested collections, and the need for commas. Guessing this might be correct:

ATTR collection media-col-ready { MEMBER collection media-size { MEMBER integer x-dimension 21590, MEMBER integer y-dimension 27940 }, MEMBER integer media-top-margin 423, MEMBER integer media-bottom-margin 423, MEMBER integer media-left-margin 423, MEMBER integer media-right-margin 423, MEMBER keyword media-source "main", MEMBER keyword media-type "stationery" }

(Is it possible for parsing errors to be written out to the ippserver log? That would help too...)

**Comment by wifiprintguy** [comment]
Pete Zehler brought this to my attention, BTW...

**Comment by michaelrsweet** [comment]
Your example is almost correct. Try (also showing a second collection value):

```
ATTR collection media-col-ready {
    MEMBER keyword media-key "na_letter_8.5x11in_main"
    MEMBER name media-info "Letter in Main Tray"
    MEMBER collection media-size {
        MEMBER integer x-dimension 21590
        MEMBER integer y-dimension 27940
    }
    MEMBER keyword media-size-name "na_letter_8.5x11in"
    MEMBER integer media-top-margin 423
    MEMBER integer media-bottom-margin 423
    MEMBER integer media-left-margin 423
    MEMBER integer media-right-margin 423
    MEMBER keyword media-source "main"
    MEMBER keyword media-type "stationery"
},{
    MEMBER keyword media-key "iso_a4_210x297mm_alternate"
    MEMBER name media-info "A4 in Alternate Tray"
    MEMBER collection media-size {
        MEMBER integer x-dimension 21000
        MEMBER integer y-dimension 29700
    }
    MEMBER keyword media-size-name "iso_a4_210x297mm"
    MEMBER integer media-top-margin 423
    MEMBER integer media-bottom-margin 423
    MEMBER integer media-left-margin 423
    MEMBER integer media-right-margin 423
    MEMBER keyword media-source "alternate"
    MEMBER keyword media-type "stationery"
}
```

**Comment by wifiprintguy** [comment]
ok so:
1) it is OK to spread the declarations out across multiple lines
2) member peers within a collection don't need to be delimited with commas

**Comment by michaelrsweet** [comment]
Right, values are separated by commas, not attributes.

**Comment by michaelrsweet** [comment]
[master 76d84c0] Add collection example to ipptoolfile man page (Issue #16)
