### ISSUE TITLE
ippserver: SERVERPORT is 0 when "Listen" directive is in system.conf

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#166]
If you have a system.conf with this in it:

`Listen *:8900

and you have a "test.conf" in print with this in it:

`ATTR textWithoutLanguage  printer-location "IPP on $SERVERNAME at port $SERVERPORT"

then if you run ippserver to use those files, you should see output including "IPP on serenity.localdomain at port 0".

Notice the port number doesn't match what is in the system.conf. If you then comment out the "Listen" directive in system.conf, you should see output including "IPP on serenity.localdomain at port XXXX" where XXXX is the port that ippserver dynamically selects.

**Comment by michaelrsweet** [comment]
Hmm, this should work...  Investigating...

**Comment by michaelrsweet** [comment]
Wasn't setting the variable when parsing the Listen directive...
