### ISSUE TITLE
ippserver: difficulty constructing a path to a resource to be served up by ippserver

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#167]
If you use the SERVERNAME and SERVERPORT keywords from ippserver in your .conf file, and you want to make a file such as an ICC profile available, it isn't clear how you would do this. 

So if you do this:

1. Have this in your printer.conf file:

```
ATTR collection       printer-icc-profiles
{
    MEMBER nameWithoutLanguage  profile-name            "Adobe RGB 1998"
    MEMBER uri                  profile-uri             "http://$SERVERNAME:$SERVERPORT/AdobeRGB1998.icc"
    MEMBER keyword              media-type              "photographic-glossy"
    MEMBER enum                 print-quality           5 # high
},
{
    MEMBER nameWithoutLanguage  profile-name            "sRGB A"
    MEMBER uri                  profile-uri             "http://$SERVERNAME:$SERVERPORT/sRGB_A.icc"
    MEMBER keyword              media-type              "paper"
},
{
    MEMBER nameWithoutLanguage  profile-name            "sRGB A"
    MEMBER uri                  profile-uri             "http://$SERVERNAME:$SERVERPORT/sRGB_A.icc"
    MEMBER keyword              media-type              "com.hp.ecosmart-lite"
}

```

2. Run ippserver using the printer.conf file, etc.
3. Try to get to one of the files using a tool like curl, a web browser, etc.

Expected result: The file is reachable

Actual result: You won't be able to get the file.

The issue seems to be that ippserver is not serving up the file. I've tried the equivalent of:

* http://$SERVERNAME:$SERVERPORT/sRGB_A.icc
* http://$SERVERNAME:$SERVERPORT/ipp/sRGB_A.icc
* http://$SERVERNAME:$SERVERPORT/ipp/print/sRGB_A.icc
* http://$SERVERNAME:$SERVERPORT/ipp/print/printer/sRGB_A.icc

And with all of them I get either a 200 OK and no ICC file, or I get a 404 Not Found.

**Comment by michaelrsweet** [comment]
Investigating...

**Comment by michaelrsweet** [comment]
OK, right now the list of resources is basically hardcoded - /ipp/print/name/icon.png and /ipp/print/name/ll.strings (where "ll" is a language). I'll update the code to support ICC color profiles as well (as statically-configured resources when the system is loaded) so then they'll be of the form "/ipp/print/name/profile.icc".

**Comment by michaelrsweet** [comment]
Actually, I'm going to add a PROFILE directive so that the server can manage the remote filenames, like we do for STRINGS.

**Comment by michaelrsweet** [comment]
OK, changes are now in master, with sample ICC profiles for the ipp-everywhere-raster printer.
