### ISSUE TITLE
Add support for "printer-strings-uri" attribute / resource location

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#17]
It would be good to have a way to allow the Printer to specify a legitimate value for the "printer-strings-uri" attribute, so that strings files could be used by the Client.

**Comment by michaelrsweet** [comment]
OK, this is now done.

**Comment by michaelrsweet** [comment]
Add the following to the conf files for each supported language/strings file:

    Strings lang filename.strings
