### ISSUE TITLE
ippserver: Starting two instances with no specified port will cause the second one to crash because port is in use

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#170]
If you run ippserver  from two different shells, the second one will crash with a SIGSEGV, presumably because the port is in use by the first one, and there are no "port in use - move to the next one" semantics.

**Comment by michaelrsweet** [comment]
We might be able to do something here, holding for post-1.0.

**Comment by michaelrsweet** [comment]
[master 24bc852] When using the default port, keep trying until an open port is found (Issue #170)
