### ISSUE TITLE
How to run IPP Shared Infrastructure Extensions to act as an intermediary between clients and printers

### ISSUE THREAD

**Issue by GreatBahram** [istopwg/ippsample#171]
According to the IPP everywhere documentation, it's possible to run `Cloud, Enterprise, and Managed Printing` by using this package, right? The scenario has been described in this [link](https://www.pwg.org/ipp/everywhere.html)

I want to run something like that, but there are quit a few problems. Firstly, Imagine I have an old printer which does not support IPP, the only thing I had is a ppd file. I want share this printer in a way users do not need to install any drivers based on their OS. it seems IPP everywhere can achieve this goal. The problem is `ippserver` does not have any option for reading the attributes from a ppd file?
* is there any way to generate the attributes-file (`-a`) for the `ippserver` command from ppd file?
* Could I bind `ippserver` with cups `device-uri`, I want to receive prints via `ippserver` but sends them for the real backend printer?

Finally, why you called this package `ippsample`? is this a long-support package or just a simple implementation?
And if you see any problem in this scenario which I might encounter in the future or you don't understand any part of it, let me know.

**Comment by michaelrsweet** [comment]
@GreatBahram This IPP Sample Code project is just that - sample code showing how to implement IPP and tools for testing your implementation of IPP. Unlike CUPS, this project is not about providing a turn-key solution for printing.

WRT PPD files, a future release of CUPS will include a new version of the one-file ippserver program (now called ippeveprinter to avoid confusion with the ippsample project's much more complete ippserver program) that can read a PPD file, at least for supporting PostScript printers, but it will *not* handle everything for a deprecated CUPS printer driver and does not emulate the old CUPS printer driver interface.
