### ISSUE TITLE
cupsFilePrintf overflows, if print_attr comes along with char[] more than printf_buffer can hold

### ISSUE THREAD

**Issue by martinwetzko** [istopwg/ippsample#172]
https://github.com/istopwg/ippsample/blob/81e345304e12de22ca70d234337322219ffb0667/cups/file.c#L1378

will return -1 on windows, if the fp->printf_size is less than ap holds. This is later converted to unsigned int in the cups_write, so the console tries to print an infinite number of bytes.

Reproducable with ipp-1.1.test:

https://github.com/istopwg/ippsample/blob/81e345304e12de22ca70d234337322219ffb0667/examples/ipp-1.1.test#L211

If the server returns multiple values for that attribute, which later is concatenated to a string with more than 1024 chars.

**Comment by michaelrsweet** [comment]
@martinwetzko This appears to be a MSVC runtime bug - their vsnprintf implementation does not conforming to the C99 interface so we'll need to use our vsnprintf implementation instead.

**Comment by michaelrsweet** [comment]
[master dcbcf0a] Don't use Windows implementation of snprintf/vsnprinf since they do not conform to C99... (Issue #172)
