### ISSUE TITLE
ippserver: "printer-state-reasons" = 'paused' on startup, cannot clear that with Resume-Printer

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#180]
When I run ippserver, the Printers it hosts have "printer-state-reasons" = 'paused'. I cannot seem to clear it with a Resume-Printer operation (as per the resume-printer.test file attached). Not sure if there are other ways to influence the Printer's state reasons.

[resume-printer.test.txt](https://github.com/istopwg/ippsample/files/3139007/resume-printer.test.txt)

**Comment by michaelrsweet** [comment]
Strange, the code certainly looks like it is doing the right thing. Investigating further...

**Comment by michaelrsweet** [comment]
OK, the problem is limited to initially configured printers - the state-reasons values are not getting cleared when the existing printer state is set to idle. Resume-Printer doesn't change anything because the state isn't "stopped"... :/

**Comment by michaelrsweet** [comment]
[master 27e9e41] Loaded printers need to have their reasons cleared (Issue #180)
