### ISSUE TITLE
Windows end of line issue

### ISSUE THREAD

**Issue by ameurenand** [istopwg/ippsample#181]
Hi,
I compiled ippsample project on Windows and I noticed some EOL issue (CRLF instead of LF) on output job file.
When you use _write method, you have to add _O_BINARY flag else each LF character is replaced with a CRLF pair in the output.
Regards

**Comment by michaelrsweet** [comment]
[master 441587f] Add O_BINARY flag to all open calls that expect to read/write binary data (Issue #181)

**Comment by ken-sands** [comment]
This problem still exists in the ippeveprinter
