### ISSUE TITLE
Add framework for integration testing

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#182]
The "make test" target currently runs the test/run-tests.sh script which has "Coming soon".

For testing ippserver and ippproxy, we will need to devise a way that ippserver can be launched (./test/start-server.sh), a given Printer can be identified (via ippfind) and targeted by an ipptool and .test file combination. At its completion, the ippserver should be terminated. If this framework could be modularized such that a "template script" could be made that takes a .test and reports the results to run-tests.sh and make, that would mean it could be easily extended.

**Comment by michaelrsweet** [comment]
[master 1e46a3b] Initial integration test suite (Issue #182)
