### ISSUE TITLE
ipptool: Reusing the same random request-id for all requests

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#188]
From reading the "ipptoolfile" man page, ipptool is supposed to generate a new random request ID by default. In other words, including "REQUEST-ID random" in the .test file is the same as not having any "REQUEST-ID" statement in there at all.

Unfortunately, the default behavior seems to be to generate a random ID at startup, and then keep reusing that same ID over and over again. That causes some confusion in Wireshark, among other things...

I think the logic problem is with the lines 3143-3164 in ipptool.c, in the function "token_cb()".

**Comment by michaelrsweet** [comment]
Hmm, it should start out random and then increment. Investigating.

**Comment by michaelrsweet** [comment]
OK, the issue is that if we repeat a test we don't increment the request ID. Simple enough fix...

**Comment by michaelrsweet** [comment]
[master 9423d4b] Sync up with CUPS 2.4.0 changes.
