### ISSUE TITLE
ippfind: add an argument for exact name matching

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#19]
The ippfind tool has the "-n" and "--name" options to specify the name. But these are regular expressions. It would be very useful for some users and some uses of ippfind (such as the IPP Everywhere Self Certification tool suite) if there was a different argument that would specify the exact name string, that didn't require all the escaping, etc. that a regular expression would require. The new argument could perhaps use the "-e" / "--exact-name" label.

**Comment by michaelrsweet** [comment]
Or "-N" / "--literal-name".

**Comment by michaelrsweet** [comment]
[master a4ea9b9] Add -N/--literal-name options for literal name matching (Issue #19)

Also, the following already worked:

    ippfind "Name of Printer._ipp._tcp" ...
