### ISSUE TITLE
ipptool: Add predicate for testing the number of occurrences of an attribute

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/ippsample#191]
One of our GSoC students asked about the ability to test the number of objects that operations like Get-Jobs return, however ipptool cannot do that yet.

Suggested syntax would be something like:

    EXPECT-ALL attribute OCCURS 42
    EXPECT-ALL attribute OCCURS >1
    EXPECT-ALL attribute OCCURS <42

The OCCURS predicate would count the number of occurrences and then compare equality (42), greater than (>1), or less than (<42).

Would also be useful for validating support for the limit attribute...

**Comment by wifiprintguy** [comment]
+1
