### ISSUE TITLE
ippserver: 'false' for "last-document" in Send-Document request returns error

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#193]
If a .test file performs a Create-Job followed by a Send-Document, and the Send-Document operation includes:

    ATTR boolean last-document false

The ippserver will respond with:

        status-code = client-error-attributes-or-values-not-supported (Unsupported last-document boolean value.)
        EXPECTED: STATUS successful-ok (got client-error-attributes-or-values-not-supported)
        status-message="Unsupported last-document boolean value."

**Comment by michaelrsweet** [comment]
This is correct - at present ippserver does not support multiple document jobs... :/

**Comment by wifiprintguy** [comment]
Agree with resolution - my bad! 😊
