### ISSUE TITLE
ipptool: "Cancel-My-Jobs" with "job-ids" sends malformed request

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#2]
If a Cancel-My-Jobs operation is performed and the "job-ids" attribute is provided, with a value containing more than one legitimate Job ID, ipptool will not put the first Job ID, but will rather send a zero (0).  This will cause the operation to fail at best, and at worst, will prevent the jobs from being cancelled.

In the attached "cancel-my-jobs.test.txt" test file, a Cancel-My-Jobs operation is performed.  The "job-ids" optional operation attribute is provided, whose value lists the 3 Job IDs of the jobs that are created earlier in the test.

[cancel-my-jobs.test.txt](https://github.com/istopwg/ippsample/files/271351/cancel-my-jobs.test.txt)

**Comment by michaelrsweet** [comment]
Hmm, what is strange is that ipptool compiled on OS X from this project does not show this problem. What version of ipptool are you using?

**Comment by wifiprintguy** [comment]
Sorry, should have checked with the latest version that is in this project.  The version I was using was /usr/bin/ipptool in 10.11.5 (cups v2.1.0 release) and the version in ippeveselfcert project, so we need to get these versions of ipptool and ippfind pushed over to that other project or link them (Git now supports something similar to Subversion Externals, I believe).

**Comment by wifiprintguy** [comment]
[cancel-my-jobs-2.test.txt](https://github.com/istopwg/ippsample/files/294333/cancel-my-jobs-2.test.txt)

Additional test file that exercises this problem.
