### ISSUE TITLE
Automatic port selection in ippeveprinter.

### ISSUE THREAD

**Issue by dheeraj135** [istopwg/ippsample#204]
Issue #170 for ippeveprinter utility. 
Right now I am using a wrapper function which finds an available port but it is prone to race condition because of the time gap between finding an available port and port getting acquired by the ippeveprinter utility. So, changes need to be incorporated in the ippeveprinter itself.

**Comment by michaelrsweet** [comment]
@dheeraj135 I do not understand - if you specify a port, ippeveprinter uses it. If you do not, ippeveprinter finds an available port. What is your expectation here?

**Comment by dheeraj135** [comment]
@michaelrsweet If no port is specified and the default port(8000 in my case) is in use, then ippeveprinter exits. We can add ippserver type fallback mechanism which searches for an empty port. This issue was reported for ippserver in #170. 
When the port number is not specified, ippeveprinter does not search for an available port, it tries only on the default port.

**Comment by michaelrsweet** [comment]
OK, I see. Yes, we can update the ippeveprinter code to search for a port just as ippserver does.

**Comment by michaelrsweet** [comment]
[master 8b3fdab] Merge changes from CUPS master@ac90b74470f327463b93804b8442b82f6219cba8

**Comment by amartyapandey7681** [comment]
I have unsubscribed from the mail. Still i am getting mails. Pls look into
it.

**Comment by wifiprintguy** [comment]
@amartyapandey7681 If you load this GitHub issue into your browser it still shows you as subscribed. If the email link to unsubscribe doesn't work (GitHub problem, not ours) then load the page and unsubscribe using the button there.
