### ISSUE TITLE
Fix: Cross compile for Android/bionic_libc error on clang (server/conf.c)

### ISSUE THREAD

**Issue by ron42** [istopwg/ippsample#205]
The makefile in server/ fails to compile conf.c with clang against bionic libc:

<code>
Compiling conf.c...
conf.c:2547:37: error: 'realpath' output parameter
      must be NULL or a pointer to a buffer with >=
      PATH_MAX bytes
          dir = realpath(dir, dirabs);
                                    ^
/usr/include/bits/fortify/stdlib.h:41:9: note:
      from 'diagnose_if' attribute on 'realpath':
  ...__clang_error_if(__bos(resolved) != __BIONIC_FORTIFY_UNKNOWN_SIZE &&
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/cdefs.h:133:52: note:
      expanded from macro '__clang_error_if'
  ...msg) __attribute__((diagnose_if(cond, msg, "e...
                         ^           ~~~~
1 error generated.
make: *** [../Makedefs:142: conf.o] Error 1
</code>

Here is a patch I created:

https://pastebin.com/raw/Gqftj2tq

**Comment by ron42** [comment]
I'm terribly sorry because:
A) After having fixed the code, I forgot the exact compiler error.
B) I was too lazy to submit a PR myself
C) The github markdown messed  up the above patch (it's just that 256 --> PATH_MAX + 1 ; I'm sure that can be made out).

**Comment by michaelrsweet** [comment]
[master e8620e7] Fix compile error on Android (Issue #205)
