### ISSUE TITLE
ippserver not working correctly on systems with no wheel group

### ISSUE THREAD

**Issue by jfrsw** [istopwg/ippsample#207]
With the default configuration provided for testing the infrastructure printer (`AuthProxyGroup wheel` on `test/print/infra.conf`), when `ippserver` is started on systems with no `wheel` group the proxying features break (`ippproxy` will not get any job notifications).

Those systems include Debian and its derivatives, specially Ubuntu, which is currently used as a base for the Docker image, so trying to test the ippserver and ippproxy tools together using the provided Docker image as is will not work. Perhaps the default value for `AuthProxyGroup` could be changed to a different group (`sudo` seems to be the equivalent for Debian systems and derivatives), at least for the Docker image case.

**Comment by michaelrsweet** [comment]
[master 5964c7b] Add support for "@system" group name, which maps to the primary group ID of the user running the server (Issue #207)
