### ISSUE TITLE
ippserver: Duplicate "notify-lease-duration-default" attribute in printer-attributes-tag group

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#21]
If you run ippserver with an appropriate configuration (sample configuration attached - unzip and run 'start-server.sh') and run the IPP Everywhere Self Certification test suite's "bonjour-tests.sh" script against it, test B-4 fails with the explanation 'Duplicate "notify-lease-duration-default" attribute in printer-attributes-tag group'.

Here is sample output:

neuromancer: sw-ippeveselfcert10-smitty [1662]$ ./bonjour-tests.sh '_IPP Everywhere Basic_'
B-1. IPP Browse test: PASS
B-2. IPP TXT keys test: PASS
B-3. IPP Resolve test: PASS
B-4. IPP TXT values test: FAIL
"bonjour-value-tests.test":
    Validate TXT record values using Get-Printer-Attributes              [FAIL]
        RECEIVED: 7149 bytes in response
        status-code = successful-ok (successful-ok)
        Duplicate "notify-lease-duration-default" attribute in printer-attributes-tag group
B-5. TLS tests: SKIP
B-5.1 HTTP Upgrade test: SKIP
B-5.2 IPPS Browse test: SKIP
B-5.3 IPPS TXT keys test: SKIP
B-5.4 IPPS Resolve test: SKIP
B-5.5 IPPS TXT values test: SKIP
Summary: 10 tests, 3 passed, 1 failed, 6 skipped
Score: 90%
[ippserver-ipp-everywhere-basic.zip](https://github.com/istopwg/ippsample/files/524814/ippserver-ipp-everywhere-basic.zip)

**Comment by michaelrsweet** [comment]
[master 3b5b992] Fix duplicate notify-lease-duration-default attribute (Issue #21)
