### ISSUE TITLE
Build fails on FreeBSD 12.1-RELEASE (libiconv undefined symbol)

### ISSUE THREAD

**Issue by davidschlachter** [istopwg/ippsample#210]
`configure` is successful, compilation seems okay, but build fails when linking. System is FreeBSD 12.1-RELEASE-p5 x84_64.

[configure.log](https://github.com/istopwg/ippsample/files/4677367/configure.log)
[gmake.log](https://github.com/istopwg/ippsample/files/4677368/gmake.log)

libiconv is present:
````
$ pkg info | grep iconv
iconv-2.0_4                    Charset conversion library and utilities
libiconv-1.16                  Character set conversion library
````

(from `gmake.log`)
````
Linking ippserver...
ld: error: undefined symbol: libiconv_close
>>> referenced by transcode.c:49
>>>               transcode.o:(_cupsCharmapFlush) in archive ../cups/libcups.a

ld: error: undefined symbol: libiconv_close
>>> referenced by transcode.c:55
>>>               transcode.o:(_cupsCharmapFlush) in archive ../cups/libcups.a

ld: error: undefined symbol: libiconv_open
>>> referenced by transcode.c:156
>>>               transcode.o:(cupsCharsetToUTF8) in archive ../cups/libcups.a

ld: error: undefined symbol: libiconv_open
>>> referenced by transcode.c:157
>>>               transcode.o:(cupsCharsetToUTF8) in archive ../cups/libcups.a

ld: error: undefined symbol: libiconv
>>> referenced by transcode.c:167
>>>               transcode.o:(cupsCharsetToUTF8) in archive ../cups/libcups.a

ld: error: undefined symbol: libiconv_open
>>> referenced by transcode.c:285
>>>               transcode.o:(cupsUTF8ToCharset) in archive ../cups/libcups.a

ld: error: undefined symbol: libiconv_open
>>> referenced by transcode.c:286
>>>               transcode.o:(cupsUTF8ToCharset) in archive ../cups/libcups.a

ld: error: undefined symbol: libiconv
>>> referenced by transcode.c:296
>>>               transcode.o:(cupsUTF8ToCharset) in archive ../cups/libcups.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [Makefile:85: ippserver] Error 1
gmake[1]: Leaving directory '/usr/home/david/ippsample/server'
gmake: *** [Makefile:27: all] Error 1
````

**Comment by michaelrsweet** [comment]
Hmm, will look into this - libiconv will be needed on *BSD and should be included in the LIBS definition...

**Comment by michaelrsweet** [comment]
Hmm, configure.log shows that iconv_open is showing up in the default C library...

Checking whether FreeBSD's CUPS packages have any patches for this...

**Comment by michaelrsweet** [comment]
Hmm, the FreeBSD CUPS package doesn't make any changes for iconv support... Check that you have all of the CUPS dependencies listed [here](https://www.freebsd.org/cgi/ports.cgi?query=cups&stype=all&sektion=all) installed...

**Comment by davidschlachter** [comment]
Thanks, I'll take a look on a fresh VM next week and let you know.

Le ven. 3 juill. 2020 18 h 57, Michael R Sweet <notifications@github.com> a
écrit :

**Comment by davidschlachter** [comment]
I installed FreeBSD 12.1-RELEASE amd64 in a VirtualBox VM, checked out the `ports` tree, and built `cups` from source (automatically building all build and runtime dependencies as well):

````
svnlite checkout https://svn.FreeBSD.org/ports/head /usr/ports
cd /usr/ports/print/cups
make config-recursive install clean
````

I then cloned the `ippsample` repo and attempted to compile:

````
cd /root
pkg install -y git-lite
git clone https://github.com/istopwg/ippsample.git
cd ippsample
./configure
gmake
````

Build fails in the same way as previously reported:

[configure.log](https://github.com/istopwg/ippsample/files/4885990/configure.log)

[gmake.log](https://github.com/istopwg/ippsample/files/4885992/gmake.log)

**Comment by davidschlachter** [comment]
Similar build errors on FreeBSD 11.4-RELEASE (previous release, still supported) following the same steps as above.

[configure.log](https://github.com/istopwg/ippsample/files/4886157/configure.log)

[gmake.log](https://github.com/istopwg/ippsample/files/4886158/gmake.log)

**Comment by michaelrsweet** [comment]
Hmm, I got a FreeBSD 12.1 VM running and wasn't able to get the CUPS ports package to build - too many dependencies failed...

**Comment by michaelrsweet** [comment]
It would be really useful if you could provide the config.log and Makedefs file from the CUPS build you have that is working.

**Comment by davidschlachter** [comment]
When attempting to build `cups` from the [latest git snapshot](https://github.com/apple/cups/) (rather than from FreeBSD ports with associated patches), I found that building with `gcc` instead of `clang` was easier. I tried the same with `ippsample` in a fresh FreeBSD 12.1-RELEASE VM:

````
pkg install -y gcc9 gmake git-lite
git clone https://github.com/istopwg/ippsample.git
cd ippsample
# C Shell
setenv CC /usr/local/bin/gcc9
./configure
gmake
````

Build is successful with `gcc` instead of (system default) `clang`. I've submitted a pull request if you would like to document this in `BUILD.md`.

[configure.log](https://github.com/istopwg/ippsample/files/4898566/configure.log)
[Makefile.log](https://github.com/istopwg/ippsample/files/4898567/Makefile.log)
