### ISSUE TITLE
Failed to provide TLS Support

### ISSUE THREAD

**Issue by navita1837** [istopwg/ippsample#211]
Team, 
I am trying add TLS support for ippserver. and here is my system.config

Authentication No
DefaultPrinter g6m7
LogLevel Info
LogFile stderr
Listen 10.91.8.107:8000
Encryption Required
DataDir /home/navi12/ipp_ssl/data

and print config

Make "PWG"
Model "IP Test Printer"
DeviceURI "ipps://10.91.8.107:8000/ipp/print/g6m7"

with above configure. I could n't add printer to windows environment. 
I could add with http not with https
One observation:
Printer-uri is still logged as printer-uri="ipp://10.91.8.107:8000/ipp/print/g6m7"

**Comment by michaelrsweet** [comment]
What OS are you running ippserver on?

Can you provide a copy of the config.log file?

**Comment by navita1837** [comment]
@michaelrsweet : Thank you so much for responding. Problem is resolved.
Reason: Problem is with Certificate. Because of date miss match. Cerificate is expired. So i couldn't add ippserver from windows.  

Now I am trying to enable user authentication while printing.
I am using generic/text only driver for text prin in windowst. I have my print server i.e ippserver PWG running in Ubuntu. I tried to install the same printer using printer uri by selecting generic/text only driver. I was succeeded to give print. Now i need to provide user authentication while giving print. I didn't get any clue to give authentication using generic/text only driver. Could any one help me to achieve authenticated print using generic/text only driver. Or suggest any other driver which can support both text print and user authentication??
Config file is attached.
Could you please help me to achieve user authentication for ippserver?

[system.txt](https://github.com/istopwg/ippsample/files/4778658/system.txt)

**Comment by michaelrsweet** [comment]
Sadly, Windows doesn't support authentication using IPP...

**Comment by navita1837** [comment]
@michaelrsweet : Thank you for the information.
