### ISSUE TITLE
"ipptool" is not sending print job data in gzip format.

### ISSUE THREAD

**Issue by sahusara** [istopwg/ippsample#213]
I am trying to send a print-job using "ipptool".
Print job file is compressed using "gzip".

But, it looks like "ipptool" is sending uncompressed data over the network. 

I have attached the network trace as well as the print job file. 

ipptool --version
CUPS v2.1.3
[ipp.zip](https://github.com/istopwg/ippsample/files/4869894/ipp.zip)

**Comment by michaelrsweet** [comment]
You aren't using the ippsample version of ipptool... Regardless, if you can attach the .test file you are using then I can either confirm the problem doesn't exist in ippsample or that there is an issue with the test file.

FWIW, CUPS 2.1.3 is old and may not support gzip via ipptool like the current ipptool in ippsample does.

**Comment by sahusara** [comment]
Thanks Michael for quick response. 

Below line was missing in my .test file. Because of which the tool was not compressing the data before sending it.
"COMPRESSION gzip"

Also, I was not aware that, the tool is smart enough to compress the file. I was trying to send the .gz file.
I have tested in 3 different version of the tool, it works in all the version.

Please close this "issue".

**Comment by sahusara** [comment]
Closing the issue.
