### ISSUE TITLE
Incorrect gmtime_s call in server/log.c

### ISSUE THREAD

**Issue by chriskushmonotype** [istopwg/ippsample#217]
The calls to [`gmtime_s`](https://github.com/istopwg/ippsample/commit/91d11ede5abe9fa10b913f6b297469fe4c2fd8dc#diff-bc293540e0807282fe06a35568ddc6f6R229) and [`gmtime_r`](https://github.com/istopwg/ippsample/commit/91d11ede5abe9fa10b913f6b297469fe4c2fd8dc#diff-bc293540e0807282fe06a35568ddc6f6R232) appear to have the arguments in the [wrong order](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/gmtime-s-gmtime32-s-gmtime64-s?view=vs-2019); the `struct tm` pointer should come first, and then the `time_t`.

**Comment by michaelrsweet** [comment]
Um, according to `man` gmtime_r is defined as:

```
struct tm *
gmtime_r(const time_t *clock, struct tm *result);
```

so that usage is correct as I would expect, since both my local builds and the various CI builds are not failing.

However, it does look like Microsoft swapped the order of arguments for their version (gmtime_s) of the POSIX gmtime_r... Will fix.

**Comment by michaelrsweet** [comment]
[master 108646d] Fix order of arguments to gmtime_s on Windows (opposite of POSIX gmtime_r)
