### ISSUE TITLE
ippserver: "ippserver -C test" doesn't work on Windows

### ISSUE THREAD

**Issue by sicklittlemonkey** [istopwg/ippsample#228]
IPP Server has a nice configuration framework which works on Linux. Here's a log for the included test config:

> 2021-05-21T02:03:17.726Z  Using default data directory "/tmp/ippserver.20487".
> 2021-05-21T02:03:17.726Z  Using default spool directory "/tmp/ippserver.20487".
> 2021-05-21T02:03:17.736Z  Using default listeners for ubuntu:8000.
> 2021-05-21T02:03:17.749Z  Loading printers from "test/system.conf".
> 2021-05-21T02:03:17.750Z  Loading printer from "ippserver-data-type-test.conf".
> 2021-05-21T02:03:17.750Z  [Printer ippserver-data-type-test] printer-uri="ipp://ubuntu:8000/ipp/print/ippserver-data-type-test"
> 2021-05-21T02:03:17.762Z  Loading printer from "ipp-everywhere-raster.conf".
> 2021-05-21T02:03:17.764Z  [Printer ipp-everywhere-raster] printer-uri="ipp://ubuntu:8000/ipp/print/ipp-everywhere-raster"
> 2021-05-21T02:03:17.784Z  Loading printer from "ipp-everywhere-pdf.conf".
> 2021-05-21T02:03:17.786Z  [Printer ipp-everywhere-pdf] printer-uri="ipp://ubuntu:8000/ipp/print/ipp-everywhere-pdf"
> 2021-05-21T02:03:17.801Z  Loading printer from "foo.conf".
> 2021-05-21T02:03:17.801Z  [Printer foo] printer-uri="ipp://ubuntu:8000/ipp/print/foo"
> 2021-05-21T02:03:17.817Z  Loading printer from "infra.conf".
> 2021-05-21T02:03:17.817Z  [Printer infra] printer-uri="ipp://ubuntu:8000/ipp/print/infra"
> 2021-05-21T02:03:17.828Z  Loading 3D printers from "test/print/infra.conf".
> 2021-05-21T02:03:17.828Z  Loading 3D printer from "foo3d.conf".
> 2021-05-21T02:03:17.828Z  [Printer foo3d] printer-uri="ipp://ubuntu:8000/ipp/print3d/foo3d"
> 2021-05-21T02:03:18.685Z  [Client 1] Accepted connection from "172.25.11.8".
> 2021-05-21T02:03:18.685Z  [Client 1] POST /ipp/print/ipp-everywhere-raster
> 2021-05-21T02:03:18.685Z  [Client 1] Continue
> 2021-05-21T02:03:18.685Z  [Client 1] Get-Printer-Attributes successful-ok
> 2021-05-21T02:03:18.686Z  [Client 1] OK
> 2021-05-21T02:03:18.687Z  [Client 1] Client closed connection.
> 2021-05-21T02:03:18.687Z  [Client 1] Closing connection from "172.25.11.8".
> 2021-05-21T02:03:18.773Z  [Client 2] Accepted connection from "172.25.11.8".
> 2021-05-21T02:03:18.773Z  [Client 2] POST /ipp/print/ipp-everywhere-pdf
> 2021-05-21T02:03:18.773Z  [Client 2] Continue
> 2021-05-21T02:03:18.773Z  [Client 2] Get-Printer-Attributes successful-ok
> 2021-05-21T02:03:18.774Z  [Client 2] OK
> 2021-05-21T02:03:18.775Z  [Client 2] Client closed connection.
> 2021-05-21T02:03:18.775Z  [Client 2] Closing connection from "172.25.11.8".

But on Windows it fails to load the test configuration:

> 2021-05-21T02:28:55.729Z  Using default data directory "C:\\Users\\nick\\AppData\\Local\\Temp/ippserver.26856".
> 2021-05-21T02:28:55.730Z  Using default spool directory "C:\\Users\\nick\\AppData\\Local\\Temp/ippserver.26856".
> 2021-05-21T02:28:55.740Z  Using default listeners for localhost:8631.
> 2021-05-21T02:28:55.741Z  Loading printers from "test/system.conf".
> 2021-05-21T02:28:55.742Z  Skipping "print".
> 2021-05-21T02:28:55.742Z  Loading 3D printers from "test/system.conf".
> 2021-05-21T02:28:55.742Z  Skipping "print3d".

**Comment by michaelrsweet** [comment]
@sicklittlemonkey Will investigate once I get the other changes in. Sadly, Windows is a bit crippled compared to POSIX for certain aspects of ippserver (like running commands) and may not work out-of-the-box for all things.

**Comment by michaelrsweet** [comment]
@sicklittlemonkey Please let me know if the latest round of changes has fixed things for you...
