### ISSUE TITLE
Sockets initialization on WIndows

### ISSUE THREAD

**Issue by g41797** [istopwg/ippsample#230]
OS: Windows 10 20H2 64bits

Command line: .\ippserver.exe --no-dns-sd -v "IPPSAMPLE"

Output:
2021-06-01T09:52:45.390Z  Unable to listen on address "(null)": No such file or directory
2021-06-01T09:53:07.011Z  Unable to listen on address "127.0.0.1": No such file or directory

Reason: failure in creation of socket
/*
  * Create the socket and set options...
  */

  if ((fd = socket(addr->addr.sa_family, SOCK_STREAM, 0)) < 0)
  {
    /*^^^ ^^^*/ Added during debugging
	int
	sockError	= WSAGetLastError(); ==> 10093 (WSANOTINITIALISED)
	/*^^^ ^^^*/
	_cupsSetHTTPError(HTTP_STATUS_ERROR);
    return (-1);
  }

Clarification: 
- On WIndows WSAStartup should be called once before working with sockets
- WSAStartup called in httpInitialize(...) , but seems it's too late 

Temporary fix:
	if (DNSSDEnabled)
	{	
		dnssd_init();
	}
	/*^^^ ^^^*/
	else
	{
		WSADATA wsaData;
		int iResult;

		// Initialize Winsock
		iResult = WSAStartup(MAKEWORD(2, 2), &wsaData);
		if (iResult != 0) {
			printf("WSAStartup failed: %d\n", iResult);
		}
	}
	/*^^^ ^^^*/

As a rule ippserver works with mDnsResponder, and socket initialization done within dns client library.

**Comment by michaelrsweet** [comment]
Seems like maybe we should move the WSAStartup calls to http-addrlist.c which handles both connecting and listening sockets. Will investigate (with the core issue being addressed in the CUPS project and then merged here...)

**Comment by g41797** [comment]
super
thanks a lot
georgy

**Comment by michaelrsweet** [comment]
[master 00181de] Merge changes from CUPS master@a5687bd03d3856de83ccdc01305f5ecd8804027e
