### ISSUE TITLE
Sockets initialization on WIndows

### ISSUE THREAD

**Issue by g41797** [istopwg/ippsample#231]
#230 ==>

Command line: .\ippserver.exe --no-dns-sd -v -C configdir

System.config:
   Listen 10.214.214.82:8631

   if ((error = getaddrinfo(hostname, service, &hints, &results)) == 0)  [httpAddrGetList] 

     gataddrinfo failed with the same error 10093 (WSANOTINITIALISED)

**Comment by michaelrsweet** [comment]
[master df83ad3] Merge changes from CUPS master@00e46e36e8ba4cbd7ba8e39664b74aa7c87c6b1b
