### ISSUE TITLE
ippserver crashes during Print-Job

### ISSUE THREAD

**Issue by g41797** [istopwg/ippsample#232]
Code: conf.c

server_printer_t *			/* O - Printer or NULL */
serverFindPrinter(const char *resource)	

...........................................
   /*
    * Just use the first printer...
    */

    match = cupsArrayFirst(Printers); <=== For printer-less configuration  match == NULL
    if (strcmp(match->resource!!!EXCEPTION!!!, resource) && strcmp(resource, "/ipp/print"))
      match = NULL;

I understand that it's not a bug: it is not production code and as far as I understand dynamic configuration
(CUPS-Add-Modify-Printer/CUPS-Delete-Printer) is not supported - at least one printer should be configured.

In our system, user allowed to create "virtual" printers with different capabilities, these printers created and deleted on the fly.
Theoretically there is situation (QA style) that all printers were deleted. Also it happens during start of the print server - because delay in registration of virtual printers.

seems that function should not fail and should return NULL - rest of ippserver code works fine  for this case

if (match && strcmp(match->resource, resource) && strcmp(resource, "/ipp/print"))........

Thanks

**Comment by michaelrsweet** [comment]
@g41797 The ippserver program supports the System Service operations Create-Printer, Register-Output-Device, and Delete-Printer to create and delete print services instead of the CUPS extensions.

That said, it shouldn't crash when you have no printers configured.

**Comment by michaelrsweet** [comment]
[master 49995f8] Fix crash when there are no printers (Issue #232)
