### ISSUE TITLE
ipptransform: PWG raster output types like black_16, srgb_16, device1_16 not supported

### ISSUE THREAD

**Issue by harshitbagaria** [istopwg/ippsample#234]
PWG raster supports various output color models like black_16, srgb_16, device*_* etc, but the ipptransform tool only supports limited color models.
Types: black_1, black_8, cmyk_8, sgray_1, sgray_8, srgb_8

Is it possible to add support for other color models as well.

OS: Ubuntu 20.04 LTS (Focal Fossa)
Currently using the dockerfile provided in the repo to launch the instance.

**Comment by michaelrsweet** [comment]
@harshitbagaria Sorry, MuPDF doesn't support the full range of color spaces or bit depths, so ipptransform can't generate them.

**Comment by harshitbagaria** [comment]
@michaelrsweet Can you suggest any alternate method to generate PWG rasters with full range of color spaces?

**Comment by michaelrsweet** [comment]
@harshitbagaria Sorry, no. Using ipptransform on a Mac (which uses CoreGraphics to render the PDF) will give you 16-bit per component support, but I'm not aware of any solution that will generate arbitrary Device-N output (nor are there printers that currently accept it...)
