### ISSUE TITLE
make-pwg-samples.sh: Use "pwg-raster-document-type-supported" keywords in filenames and paths

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#238]
The script produces files with elements in them that look similar to the keywords defined for "pwg-raster-document-type-supported" but replaces underbars with dashes (e.g. "./pwg-raster-samples-300dpi/srgb-8/onepage-letter-srgb-8-300dpi.pwg" instead of "pwg-raster-samples-300dpi/srgb_8/onepage-letter-srgb_8-300dpi.pwg"). This requires the .test files have to define many duplicate tests.

Update the PWG Raster sample file naming convention to instead use the actual keywords for "pwg-raster-document-type-supported" to allow the test files to be simplified.

**Comment by michaelrsweet** [comment]
[master 3ef7ec5] Use PWG type names as-is in filenames (Issue #238)
