### ISSUE TITLE
Test docker image

### ISSUE THREAD

**Issue by thenewguy** [istopwg/ippsample#243]
We create a docker image.  We should run some tests against it to make sure it works as expected before uploading it

**Comment by thenewguy** [comment]
@michaelrsweet I haven't read how the test suite works.  Any suggestions for commands we can run against the image to verify all is in working order?  Is it possible to reuse any of the test suite against the built image

**Comment by michaelrsweet** [comment]
@thenewguy Right now there isn't a test suite - it's on the TODO list... :/

**Comment by thenewguy** [comment]
#242 adds some simple sanity tests that the expected commands are available and are able to be executed.  A few gotchas to fix per #244 but this minimally confirms the docker image is usable

**Comment by michaelrsweet** [comment]
@RomanWoerner I'm not sure why the build is failing now, investigating...

**Comment by michaelrsweet** [comment]
@RomanWoerner OK, I think I've fixed the build via `docker build -t ippsample .` - let me know how it works for you.

**Comment by michaelrsweet** [comment]
[master 655160d] Some Docker cleanup/clarifications.
