### ISSUE TITLE
Windows issue - Wrong path generated by serverCreateJobFilename

### ISSUE THREAD

**Issue by g41797** [istopwg/ippsample#250]
.................
/*
  * Create a filename with the job-id, job-name, and document-format (extension)...
  */

  snprintf(fname, fnamesize, "%s/%s/%d-%s.%s", SpoolDirectory, job->printer->name, job->id, name, ext);
..........................................................................

Forward slash is used as separator 
As result file operations failed on Windows 

Example:

Print.conf:
	...........
	Command		"IPPCommand.cmd"
	...........

IPPCommand.cmd:

	echo %*
		shows "C:\Users\10062573\Desktop\Temp\IPP\IPPRoot\Spool/Print/1-untitled.pdf"
	
	set PDL="%1"
	
	move /Y %PDL% %~dp1HotFolder
		
		The system cannot find the path specified.
	
	set PDL=%PDL:/=\%
		Replace / with \
		
	move /Y %PDL% %~dp1HotFolder

		1 file(s) moved.

BTW - pattern /%s/ is used in another places in the code
And result depends on tolerance of used Windows API

**Comment by michaelrsweet** [comment]
[master 84d4944] Normalize filenames on Windows (Issue #250)

**Comment by michaelrsweet** [comment]
Solution is to normalize the internal representation using forward slashes and convert to backslashes when running the external transform commands.
