### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by famince** [istopwg/ippsample#251]
[openEuler-584 ippsample]$ make 
Makefile:12: Makedefs: No such file or directory
make: *** No rule to make target 'Makedefs'.  Stop.

**Comment by michaelrsweet** [comment]
@famince See `BUILD.md`, you need to run the configure script first... :)

**Comment by famince** [comment]
configure: error: --with-tls=yes was specified but no compatible TLS libraries could be found.

**Comment by michaelrsweet** [comment]
@famince The `--with-tls` option takes values `cdsa` (macOS default) or `gnutls` (Linux default). Run `configure --help` for the list of supported options and values.

OpenSSL is currently *not* supported - support was removed from the CUPS code many years ago when all of the OpenSSL code issues came out, although it looks like we might be bringing it back for OpenSSL 3.0...
