### ISSUE TITLE
configure: error: --with-tls=yes was specified but no compatible TLS libraries could be found.

### ISSUE THREAD

**Issue by famince** [istopwg/ippsample#252]
configure: error: --with-tls=yes was specified but no compatible TLS libraries could be found.

**Comment by famince** [comment]
openssl 已经是最新版 (1.1.0l-1~deb9u4)。
libssl-dev 已经是最新版 (1.1.0l-1~deb9u4)。

**Comment by wifiprintguy** [comment]
what platform are you building on?

**Comment by wifiprintguy** [comment]
The resolution in Issue #251 also covers this
