### ISSUE TITLE
ipptool reports values from previous response when no response returned

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#256]
If ipptool is used to run two tests, and the printer never responds to the IPP operation in the second test, ipptool will report the status and other operation response values from the most recent successful response. The values should be zeroed out so that a "successful-ok" isn't presented to the user when there isn't a response returned by the printer. This is very misleading to the uninitiated.

First discovered in IPP Everywhere Self-Certification v1.1 Update 4 and reported as istopwg/ippeveselfcert#87

**Comment by michaelrsweet** [comment]
Fix is in CUPS upstream, will get merged to ippsample when we do the next merge.
