### ISSUE TITLE
ipp-everywhere.test fails when run with top-of-trunk ippsample code

### ISSUE THREAD

**Issue by ctwhittle** [istopwg/ippsample#26]
Steps to reproduce:
1. Run docker file to setup, build, and run latest ippsample code
2. Run ippserver 
![image](https://cloud.githubusercontent.com/assets/7174187/20817986/bddac7a2-b7df-11e6-95a6-abfc17971753.png)
3. Run ipptool from client
![image](https://cloud.githubusercontent.com/assets/7174187/20818011/ea2839d4-b7df-11e6-82d5-2711de3e5ac5.png)

Expected output:
All tests complete successfully (or are skipped)

Actual output snippet from client below:
![image](https://cloud.githubusercontent.com/assets/7174187/20818115/5d4bd574-b7e0-11e6-804d-17feea8b0450.png)

Comment from Mike:
- printer-config-change-{date-time,time} are explicitly supported and should be returned, and printer-icons is normally populated with a default value.  The printer-supply* attributes are currently commented out since I haven't had a chance to update that code from the original CUPS sources which only supported a single printer and canned supplies.  We *do* want ippserver to pass the self-cert tests so it can serve as an example of a conforming implementation... :)

**Comment by michaelrsweet** [comment]
[master e0826d8] Fix missing printer-config-change-[time,date-time] (Issue #26)
