### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by dimonic** [istopwg/ippsample#263]
Pull from repo, 

$ ./configure
$ make
Making all in tools...
Compiling ippfind.c...
ippfind.c: In function ‘main’:
ippfind.c:1381:21: error: ‘ippfind_srv_t’ {aka ‘struct ippfind_srv_s’} has no member named ‘ref’
 1381 |         if (!service->ref && !service->is_resolved)
      |                     ^~
ippfind.c:1430:22: error: ‘ippfind_srv_t’ {aka ‘struct ippfind_srv_s’} has no member named ‘ref’
 1430 |           if (service->ref)
      |                      ^~
ippfind.c:1435:13: warning: implicit declaration of function ‘avahi_service_resolver_free’ [-Wimplicit-function-declaration]
 1435 |             avahi_service_resolver_free(service->ref);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
ippfind.c:1435:48: error: ‘ippfind_srv_t’ {aka ‘struct ippfind_srv_s’} has no member named ‘ref’
 1435 |             avahi_service_resolver_free(service->ref);
      |                                                ^~
ippfind.c:1438:13: error: ‘ippfind_srv_t’ {aka ‘struct ippfind_srv_s’} has no member named ‘ref’
 1438 |      service->ref = NULL;
      |             ^~
ippfind.c:1446:25: error: ‘ippfind_srv_t’ {aka ‘struct ippfind_srv_s’} has no member named ‘ref’
 1446 |         else if (service->ref)
      |                         ^~
ippfind.c: In function ‘dnssd_error_string’:
ippfind.c:1746:1: warning: no return statement in function returning non-void [-Wreturn-type]
 1746 | }
      | ^
ippfind.c: In function ‘get_service’:
ippfind.c:2141:18: error: ‘kDNSServiceMaxDomainName’ undeclared (first use in this function)
 2141 |   char  fullName[kDNSServiceMaxDomainName];
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
ippfind.c:2141:18: note: each undeclared identifier is reported only once for each function it appears in
ippfind.c:2181:3: warning: implicit declaration of function ‘avahi_service_name_join’ [-Wimplicit-function-declaration]
 2181 |   avahi_service_name_join(fullName, kDNSServiceMaxDomainName, serviceName,
      |   ^~~~~~~~~~~~~~~~~~~~~~~
ippfind.c:2141:9: warning: unused variable ‘fullName’ [-Wunused-variable]
 2141 |   char  fullName[kDNSServiceMaxDomainName];
      |         ^~~~~~~~
At top level:
ippfind.c:2707:1: warning: ‘set_service_uri’ defined but not used [-Wunused-function]
 2707 | set_service_uri(ippfind_srv_t *service) /* I - Service */
      | ^~~~~~~~~~~~~~~
make[2]: *** [../Makedefs:175: ippfind.o] Error 1
make[1]: *** [Makefile:31: all] Error 1
make: *** [Makefile:26: all] Error 1

**Comment by michaelrsweet** [comment]
This is coming from [libcups](https://github.com/michaelrsweet/libcups), but unfortunately I can't transfer the issue between orgs.

More than likely you are missing the Avahi developer packages on your Linux distro, and those (or mDNSResponder or Windows 10+ DNS-SD) are now required.

**Comment by dimonic** [comment]
Thanks. I installed libavahi-core-dev, libavahi-common-dev and libavahi-client-dev and the compile completed. I guess this is for the libcups folk - but shouldn't "./configure" have complained?

**Comment by michaelrsweet** [comment]
@dimonic The libcups configure script didn't error out for the "auto" detect case, which I've now fixed. I'll be updating the libcups submodule version soon to pick up that change...
