### ISSUE TITLE
For https access, submodules fail to clone

### ISSUE THREAD

**Issue by dimonic** [istopwg/ippsample#264]
$ git clone --recurse-submodules https://github.com/istopwg/ippsample.git
Cloning into 'ippsample'...
remote: Enumerating objects: 6935, done.
remote: Counting objects: 100% (1330/1330), done.
remote: Compressing objects: 100% (632/632), done.
remote: Total 6935 (delta 755), reused 1168 (delta 600), pack-reused 5605
Receiving objects: 100% (6935/6935), 13.50 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (4856/4856), done.
Submodule 'libcups' (git@github.com:michaelrsweet/libcups.git) registered for path 'libcups'
Submodule 'pdfio' (git@github.com:michaelrsweet/pdfio.git) registered for path 'pdfio'
Cloning into '/home/ANT.AMAZON.COM/amanndom/workplace/ippsample/libcups'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:michaelrsweet/libcups.git' into submodule path '/home/ANT.AMAZON.COM/amanndom/workplace/ippsample/libcups' failed
Failed to clone 'libcups'. Retry scheduled
Cloning into '/home/ANT.AMAZON.COM/amanndom/workplace/ippsample/pdfio'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:michaelrsweet/pdfio.git' into submodule path '/home/ANT.AMAZON.COM/amanndom/workplace/ippsample/pdfio' failed
Failed to clone 'pdfio'. Retry scheduled
Cloning into '/home/ANT.AMAZON.COM/amanndom/workplace/ippsample/libcups'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:michaelrsweet/libcups.git' into submodule path '/home/ANT.AMAZON.COM/amanndom/workplace/ippsample/libcups' failed
Failed to clone 'libcups' a second time, aborting

**Comment by dimonic** [comment]
I can work around by clone ippsample first, editing .gitmodules to use the https uris as follows, 
[submodule "libcups"]
        path = libcups
        url = https://github.com/michaelrsweet/libcups.git
[submodule "pdfio"]
        path = pdfio
        url = https://github.com/michaelrsweet/pdfio.git
 then
$ git submodule init
$ git submodule update

**Comment by michaelrsweet** [comment]
Not ideal (makes it hard to push changes to pdfio or libcups from the ippsample clone) but I guess not everyone has SSH keys setup on their Github accounts...

[master 04409e8] Use https URLs for submodules (Issue #264)

**Comment by dimonic** [comment]
I don't use my personal github account when using my work machine, and so would rather not copy my keys to this machine so I prefer https when "at work". I should probably make a second github account for this purpose, but I figured the maintainer cost for using https instead of git@ is low.
