### ISSUE TITLE
Unexpected page dimensions

### ISSUE THREAD

**Issue by attah** [istopwg/ippsample#268]
After this fix (getting page output at all):
https://github.com/istopwg/ippsample/pull/267

...no matter what i throw at ipptransform i get this error (or one similar to it): 
ERROR: Unexpected page dimensions - 2481x3508 instead of 2480x3507
At first i thought it was an A4 issue, but i get it with Letter as well.

**Comment by michaelrsweet** [comment]
Xpdf or Poppler? Version?

What resolution?

This sounds like a rounding error.

**Comment by attah** [comment]
Poppler 0.86.1.

"1.pdf":
pdfinfo (from same Poppler) says: Page size:      595.28 x 841.89 pts (A4)
ERROR: Unexpected page dimensions - 2481x3508 instead of 2480x3507.

That's what i thought, but is somehow more off with letter where there shouldn't really be any need for rounding:

"2207.07413.pdf":
pdfinfo: Page size:      612 x 792 pts (letter)
ERROR: Unexpected page dimensions - 2550x3301 instead of 2480x3507.

**Comment by michaelrsweet** [comment]
Please file a bug against poppler - they are pretty obviously doing something wrong here.

The second dimensions are A4 at 300 DPI. So they are overriding the size *and* rounding wrong.

**Comment by attah** [comment]
> The second dimensions are A4 at 300 DPI. So they are overriding the size and rounding wrong.

The big error was PEBKAC, i didn't give a device-uri or option to use letter. Sorry for the noise.
I'll take the rounding error to Poppler.

**Comment by attah** [comment]
Found an old PR correcting Poppler's calculations for Letter, and they have resurrected it, but unfortunately there is still a mismatch in A4.

Could you please share what is considered correct in this context (closest/floor/ceil):
A4@300dpi (595.28 x 841.89 pt)
595.28/72*300 = 2480.333...
841.89/72*300 = 3507.875

ipptransform expected: 2480x3507
old Poppler produces: 2481 x 3508
patched Poppler produces: 2481 x 3508 (same)

So floor is the way it should work? (It sounded like you wanted closest)
Back when i used pdftoppm, i resorted to trusting it for what i the made raster dimensions and put into the PWG header.

**Comment by michaelrsweet** [comment]
@attah Floor is the correct behavior since ceil or closest (round) will sometimes produce a bitmap that is larger than the requested size.

**Comment by attah** [comment]
I'll pass it along.
And if they don't agree, there is always -scale-to-x and -scale-to-y. :/

**Comment by attah** [comment]
They did not want to change to that behavior, so i have updated the draft PR to use scaling options.
