### ISSUE TITLE
More feedback than issue for Windows build

### ISSUE THREAD

**Issue by jayjlawrence** [istopwg/ippsample#27]
I wanted a recent build of Ipptool for a project I am working on - and target platform is Windows. Various factors led me to installing VC 2015 and building the source. This is definitely not my wheelhouse so what I wanted to contribute is a bit of developer experience going from no source to build exe.

1 - Install Bonjour SDK. I do not see it on the include or lib paths so is this on the default paths in VC somewhere?

2 - Install zlib. Perhaps adding a subproject referencing https://github.com/madler/zlib would do the trick. Again I needed to add this to the include and build paths everywhere. (And I just stumbled across NuGet which I suspect makes this process 10x easier)

3 - I had to remove the three "_pwgXXXX" entries from libcups2.def. The impression is that these are deprecated functions and I expect they are not used in the 3 executables of this project.

4 - It would be nice to have a build step that brings final resources together in one directory - the dll's and exe files.

I hope this feedback on the spots where I got stuck is of value to the project!

Jay

**Comment by michaelrsweet** [comment]
Visual Studio has "global" preferences to control where to look for libraries, which is the recommended way to deal with these dependencies. I don't want to introduce sub-project references since they have their own issues... :/

I'll check on the _pwg functions; they might in fact be deprecated, but some of them are "private" API that are used for ippserver.

As for the final build step, it is possible we could build an MSI file (like we do in the self-cert project) with all of the tools, etc., but since this is supposed to just be sample code I am not 100% comfortable with that. Will talk with others in the IPP WG to get their opinions...

**Comment by michaelrsweet** [comment]
Just to follow up on this, I now plan on adding an MSI target so we can make a Windows package (or packages).

**Comment by StefanScherer** [comment]
I did a Windows compile two months ago, but newer commits here introduced eg. posix libs so I have to add more and more ifdef's for Windows.
I managed to build the sources with AppVeyor which is "like Travis, but for Windows". So everyone can see how to install all dependencies as they have immutable build agents.
If there is interest I could provide a PR to make it work in this upstream repo.

**Comment by michaelrsweet** [comment]
@StefanScherer it would be awesome for us to get automated builds, etc. for Windows. We already do this for Linux and macOS via Travis CI and snapcraft's build infrastructure...

**Comment by StefanScherer** [comment]
OK, will try to start a WIP PR to introduce AppVeyor first which obviously will have build failures. In other commits or other PR's I'll try to make the build green again.

**Comment by michaelrsweet** [comment]
@StefanScherer Sounds like a plan, thank you!

**Comment by StefanScherer** [comment]
Created PR #131, I started using NuGet packages to solve the zlib dependency as @jayjlawrence has suggested.

In previous builds I compiled zlib beside the ippsample repo and added INCLUDE and LIB pathes. But with the NuGet dependencies it looks better and nobody has to modify global settings in Visual Studio.
The NuGet dependencies are installed per .sln solution.

**Comment by michaelrsweet** [comment]
I like the NuGet solution, and will investigate what to do about the Bonjour dependencies -the SDK also includes the service so it can’t be directly packaged. Perhaps we can come up with a runtime solution to dynamically load/use bonjour if installed...

**Comment by michaelrsweet** [comment]
Smith also pointed me at a [Windows 10-specific API](https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd), although I'm not crazy about supporting yet another Bonjour API... :/

**Comment by StefanScherer** [comment]
Interesting. My 2 cents:
Pro:
- no external dependencies
Contra:
- probably only available with Windows 10
- more `#ifdef`'s in the code

**Comment by michaelrsweet** [comment]
OK, I think our current solutions for Bonjour/DNS-SD (run-time loader) and zlib (NuGet package) seem to be working well, and we have regular Windows builds using the Visual Studio on AppVeyor, so let's call this issue solved/closed...
