### ISSUE TITLE
ipptool: Add ability to perform Get-Printer-Attributes without needing a .test file

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#270]
For some diagnostics / debugging scenarios, it can be useful to ask someone to run ipptool to acquire a dump of the printer's attributes. But providing them with a .test file can be awkward. It would be helpful if ipptool supported a mode where it would perform a Get-Printer-Attributes without needing a .test file, so that it could be invoked like so:

$ ipptool --get-printer-attributes --requested-attributes=all --ippserver my-printer.conf

**Comment by michaelrsweet** [comment]
All installs provide a get-printer-attributes.test file that can be used:

```
ipptool --ippserver my-printer.conf IPP-URI get-printer-attributes.test
```
