### ISSUE TITLE
Does the ippserver created virtual ipp printer, is supported "Print Support App"

### ISSUE THREAD

**Issue by ankasani** [istopwg/ippsample#271]
Hi Team,

I have created the UWP app using
https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-design-guide

And tried to install extension using .inf with the details of ippserver added printer
https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/print-support-app-association

But this extension was not detected by the printer added by ippserver.

So, just want to check is there any suggestions on this and does it support the add extension?

I am using windows 11.

**Comment by michaelrsweet** [comment]
@ankasani I have no experience with this particular set of Windows interfaces, but AFAIK there is nothing that needs to be done on the IPP end to support it, just provide the metadata (printer-device-id, printer-make-and-model) that allows Windows to associate a IPP printer with your PSA.

You'll probably get better answers from Microsoft's developer support team on this...
