### ISSUE TITLE
ipptoolfile man page: Document method to reference collection members and logical operators for predicates

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#274]
The man page for ipptoolfile doesn't seem to clearly include a description of how a test can reference a particular member within a collection, nor does it document what logical operators can be used for the values.

For members of a collection, a "path" is used, like so:

`    EXPECT finishings-col/baling OF-TYPE collection`

It also isn't clear what logical operators the author of a .test file could use in a predicate. For instance, they might want to include an EXPECT directive like so:

`    EXPECT uri-authentication-supported OF-TYPE keyword IN-GROUP printer-attributes-tag WITH-VALUE 'basic' | 'certificate' | 'digest' | 'negotiate' | 'OAuth 2.0'`

(If the latter isn't possible then I'll file a separate enhancement request...)

**Comment by michaelrsweet** [comment]
This should be filed against the [libcups](https://github.com/OpenPrinting/libcups) project since we import ipptool from it. Thanks!

**Comment by wifiprintguy** [comment]
I'll move it over there - thanks!
