### ISSUE TITLE
Windows issue reading ipptool files 

### ISSUE THREAD

**Issue by jayjlawrence** [istopwg/ippsample#28]
A strange and intermittent issue has come up running ipptool under windows. It only came to bite me after numerous successful runs.

It seems that ftell gets confused when various getc / ungetc operations are performed on a file that is opened in mode "r" (ascii). It is necessary to open the file in mode "rb" (binary). My file on windows had simple unix style line endings which is perhaps where the inaccuracy comes about - I'm not sure. I have confirmed the fix works.

Rather than submitting a patch I'd like to offer the code location for the change as its very simple to find. I do not feel other fopen and similar calls need to be changed from "r" to "rb" at this time but I'll be on look out now!

ipptool.c
````
~ line 829:	if ((fp = fopen(testfile, "rb")) == NULL)
````

The symptoms of the problem were weird parse errors showing "incorrect tokens" from earlier in the file. And in particular due to a collection attribute. Maybe the pattern of getc / ungetc did the trick in this. Attached is a zipped file that should hopefully not work for you and then will work after the patch.

J
[testfile.zip](https://github.com/istopwg/ippsample/files/792217/testfile.zip)

**Comment by michaelrsweet** [comment]
This *is* strange.

I think the best long-term solution is to update the code to use the CUPS file API which doesn't have this issue. We've had issues in the past when reading text files in binary mode on Windows thanks to unsafe assumptions that Microsoft makes... :/

**Comment by michaelrsweet** [comment]
[master 947cefe] Migrate ipptool to use the CUPS file API to avoid some Windows line ending problems (Issue #28)
