### ISSUE TITLE
Question regarding configure failure

### ISSUE THREAD

**Issue by g41797** [istopwg/ippsample#280]
./configure     
........................
checking for pthread_create using -lpthreads... no
checking for pthread_create using -lpthread... yes
checking for zlib.h... no
checking for inflateCopy in -lz... no
configure: error: Sorry, this software requires **_ZLIB 1.1_** or higher.
configure: error: ./configure failed for **_libcups_**
..................................................................

Actually I have "clean" computer (OS - Fedora 37): it's first time C software was compiled :-(

Do I need manually install zlib?

Thanks

**Comment by michaelrsweet** [comment]
See the file "BUILD.md" - you need the zlib headers ("zlib-devel" I think) along with the other dependencies.

**Comment by g41797** [comment]
Thanks
