### ISSUE TITLE
Conversion of PDF to PCL in ipptransform not sending data back to ippserver.

### ISSUE THREAD

**Issue by AFischer4** [istopwg/ippsample#281]
Hello,
I tried to setup `ippserver` on a Raspberry Pi4 with Debian 10 to convert PDF input to PCL output with the help of `ipptransform`.

But `ipptransform` only sends back 4 bytes of PCL data, when called from `ippserver`.
When `ipptransform` is called from the command line, there is much more PCL data.

I downloaded `ippsample` "v2023.03" recently, but updated to master already.

The 4 bytes in the PCL data stream are: `<Esc>E<Esc>E`  (`\033E\033E`)
The first `<Esc>E` is from `/tools/ipptransform.c:pcl_start_job()`, 
the second `<Esc>E` is from `/tools/ipptransform.c:pcl_end_job()`
The expected PCL outputs from calls to `pcl_start_page()`, `pcl_write_line()` and `pcl_end_page()` don't show up in the PCL data stream.

As far as I found out, these calls are after `popen("pdftoppm...")` and before 
`pclose()`.

To convert PDfs to PCL, `ippserver` is calling `ipptransform`, which in a next level is calling `pdftoppm`.
The conversion result of `pdftoppm` to `ipptransform` is piped via stdout.
`ipptransform` converts the ppm data to PCL data and streams the result via stdout to the upper level `ippserver`.
But the stdout-pipe to the upper level `ippserver` is temporarily overwritten by the call of `popen(„pdftoppm…“)`.

I think `pdftoppm` must be called the same way as `ipptransform` is called from `ippserver` to solve the problem. 

Replace `popen()`/ `pclose()` with the same pattern as in `serverTransformJob()` to call `ipptransform`:
  ```
  posix_spawn_file_actions_init()
  posix_spawn_file_actions_addopen()
  posix_spawn_file_actions_adddup2()
  posix_spawn()
  posix_spawn_file_actions_destroy()
```

I have never used these functions before…

And there is another minor problem in the PCL data in `tools/ipptransform.c:pcl_end_page()`
The PCL sequence `<ESC>*r0B` (`\033*r0B`) should be replaced by `<ESC>*rB` (`\033*rB`).

The tool PCL Paraphernalia marks the actual sequence as error: „Invalid sequence: „Unexpected value field“.

—
Andreas

**Comment by michaelrsweet** [comment]
Regarding the first issue, look for errors from pdftoppm (from Poppler or Xpdf) - there are some known compatibility issues.

Regarding the PCL output, "ESC*r0B" is correct and PCL Paraphernalia is wrong - PCL 3 and 4 had an argument for the end raster graphics command while PCL 5 does not. For maximum compatibility, we need to keep the "0" argument in there.

**Comment by AFischer4** [comment]
No it’s not `pdftoppm` alone. I tried different pdf files from different producers and calling `pdftoppm` from the command line is sending valid grafic data.
And you won’t notice the error, until you try to use `ipptransform` as man-in-the-middle to directly stream the result from `pdftoppm` to the upper level `ippserver` via `stdout`. 

I think the unidirectional pipe of `popen()` is overwriting the opposite direction. 
To call `pdftoppm` all the arguments are passed by command line or environment, and the result is received via `stdin`. The opposite direction `stdout` is  during this time overwritten with /dev/null? 
That is the main reason, why `ippserver` only received 4 bytes of data.


Regarding the PCL output, ESC*r0B: 
I started with PCL5 and didn’t know about differences in previous versions. 
Besides PCL Paraphernalia another website didn’t mention the existence of differences to earlier versions.
Sorry for the noise.

**Comment by michaelrsweet** [comment]
So the `popen` call will *not* affect the standard input/output/error file descriptors of the ipptransform process and so that *isn't* the issue. Can you provide a sample PDF file you are trying to convert to PCL and the configuration you are using with ippserver?

**Comment by AFischer4** [comment]
Sorry, I was too busy and couldn't reply faster.
As I have noticed, there is a September-Update of ippsample which i used to recheck the problems.
 
It looks like to problem was actually several problems.
 
I attached the sample image, which made trouble, when I tested `ipptransform` on a RPi4 at the end of April.
It’s still causing troubles, but further down the road in `pdftoppm`.
(Maybe not your problem?!?)
 
But I couldn't reproduce missing PCL data after `pdftoppm` successfully converted PDF to graphics.
`popen()` problem disappeared?!?
Is this due to recent changes in ippsample or is it probably related to an update of my RPi4 environment?
My `libc .so.6` points to `libc-2.28.so`, which is dated after my last test. (May 25, 2023)
 
 
For the following tests I’m calling `ipptransform` directly.
I tested `pdftoppm` from poppler and from xpdf package by replacing` /usr/bin/pdftoppm` with the appropriate binary:
 
```
Test with poppler 0.71 pdftoppm:
pi@server-10:~ $ /usr/bin/pdftoppm -v
pdftoppm version 0.71.0
Copyright 2005-2018 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
 
       pi@server-10:~ $ ./ipptransform -vvv -f j1_poppler.pcl -m application/vnd.hp-pcl ./1-img-20230421-wa0001_jpg.pdf
 
DEBUG: Preparing document 1: './1-img-20230421-wa0001_jpg.pdf' (application/pdf)
DEBUG: Opening prepared document 1: './1-img-20230421-wa0001_jpg.pdf'.
DEBUG: Document 1: pages 1 to 1.
DEBUG: Using page 1 (0x559995d3e0) of document 1, cell=1/1, current=0
DEBUG: Doing full layout of 1 pages.
DEBUG: Laying out page 1/1.
DEBUG: page_dict_cb(dict=0x559995e780, key="ExtGState", outpage=0x7fc457b110), type=5
DEBUG: page_dict_cb(dict=0x559995e780, key="ProcSet", outpage=0x7fc457b110), type=1
DEBUG: page_dict_cb(dict=0x559995e780, key="XObject", outpage=0x7fc457b110), type=5
DEBUG: iwidth=595, iheight=841, cwidth=559.843, cheight=771.024, rotate=false
DEBUG: Page 1, cell 1/1, cm=[0.916794 0 0 0.916794 24.8916 35.4331], input=0x559995d3e0
DEBUG: Opening content stream 1/1...
DEBUG: Opened stream 1, resmap[0]=(nil)
DEBUG: cupsColorSpace=18
DEBUG: cupsBitsPerColor=8
DEBUG: cupsBitsPerPixel=8
DEBUG: cupsNumColors=1
DEBUG: cupsWidth=2480
DEBUG: cupsHeight=3507
ATTR: job-impressions=1
ATTR: job-pages=1
ATTR: job-media-sheets=1
DEBUG: cupsPageSize=[595.276 841.89]
DEBUG: Using Poppler version of pdftoppm.
DEBUG: Running "pdftoppm -gray -aa no -r 300 -scale-to 3507 '/tmp/6c2296da.pdf'".
Syntax Error (198): Unknown compression method in flate stream
DEBUG: 'P5'
DEBUG: '[2480 3508](tel:2480 3508)'
DEBUG: '255'
DEBUG: width=2480, height=3508, bpp=1, ystart=0, yend=3507
ATTR: job-impressions-completed=1
ATTR: job-media-sheets-completed=1
 
```
I attached the produced output file `j1_poppler.pcl`, but the contents is not as expected!
(82 Bytes of PCL Header and Trailer only.)
 
Test with xpdf 4.04 pdftoppm:
 ```
pi@server-10:~ $ /usr/bin/pdftoppm -v
pdftoppm version 4.04 [www.xpdfreader.com]
Copyright 1996-2022 Glyph & Cog, LLC
 
pi@server-10:~ $ ./ipptransform -vvv -f j1_xpdf.pcl -m application/vnd.hp-pcl ./1-img-20230421-wa0001_jpg.pdf
 
DEBUG: Preparing document 1: './1-img-20230421-wa0001_jpg.pdf' (application/pdf)
DEBUG: Opening prepared document 1: './1-img-20230421-wa0001_jpg.pdf'.
DEBUG: Document 1: pages 1 to 1.
DEBUG: Using page 1 (0x55abb433e0) of document 1, cell=1/1, current=0
DEBUG: Doing full layout of 1 pages.
DEBUG: Laying out page 1/1.
DEBUG: page_dict_cb(dict=0x55abb44780, key="ExtGState", outpage=0x7fe93541b0), type=5
DEBUG: page_dict_cb(dict=0x55abb44780, key="ProcSet", outpage=0x7fe93541b0), type=1
DEBUG: page_dict_cb(dict=0x55abb44780, key="XObject", outpage=0x7fe93541b0), type=5
DEBUG: iwidth=595, iheight=841, cwidth=559.843, cheight=771.024, rotate=false
DEBUG: Page 1, cell 1/1, cm=[0.916794 0 0 0.916794 24.8916 35.4331], input=0x55abb433e0
DEBUG: Opening content stream 1/1...
DEBUG: Opened stream 1, resmap[0]=(nil)
DEBUG: cupsColorSpace=18
DEBUG: cupsBitsPerColor=8
DEBUG: cupsBitsPerPixel=8
DEBUG: cupsNumColors=1
DEBUG: cupsWidth=2480
DEBUG: cupsHeight=3507
ATTR: job-impressions=1
ATTR: job-pages=1
ATTR: job-media-sheets=1
DEBUG: cupsPageSize=[595.276 841.89]
DEBUG: Using Xpdf version of pdftoppm.
DEBUG: Running "pdftoppm -gray -aa no -r 300 '/tmp/e70f2187.pdf' -".
Syntax Warning (197): Unknown compression method [cmf1:0x0a 78] in flate stream
Syntax Error (198): Unknown compression method in flate stream [cmf:0x0a flag:0x78]
DEBUG: 'P5'
DEBUG: '[2480 3508](tel:2480 3508)'
DEBUG: '255'
DEBUG: width=2480, height=3508, bpp=1, ystart=0, yend=3507
ATTR: job-impressions-completed=1
ATTR: job-media-sheets-completed=1
 ```
I attached the produced output file j1_xpdf.pcl. It’s bigger this time, but the contents is still wrong.
 
After I applied the changes from the attached diff-File to xpdfio, I could see reasonable results.
 ```
pi@server-10:~ $ ./ipptransform -vvv -f j1_xpdf_patched.pcl -m application/vnd.hp-pcl ./1-img-20230421-wa0001_jpg.pdf
 
DEBUG: Preparing document 1: './1-img-20230421-wa0001_jpg.pdf' (application/pdf)
DEBUG: Opening prepared document 1: './1-img-20230421-wa0001_jpg.pdf'.
DEBUG: Document 1: pages 1 to 1.
DEBUG: Using page 1 (0x5584ed03e0) of document 1, cell=1/1, current=0
DEBUG: Doing full layout of 1 pages.
DEBUG: Laying out page 1/1.
DEBUG: page_dict_cb(dict=0x5584ed1780, key="ExtGState", outpage=0x7fd9904200), type=5
DEBUG: page_dict_cb(dict=0x5584ed1780, key="ProcSet", outpage=0x7fd9904200), type=1
DEBUG: page_dict_cb(dict=0x5584ed1780, key="XObject", outpage=0x7fd9904200), type=5
DEBUG: iwidth=595, iheight=841, cwidth=559.843, cheight=771.024, rotate=false
DEBUG: Page 1, cell 1/1, cm=[0.916794 0 0 0.916794 24.8916 35.4331], input=0x5584ed03e0
DEBUG: Opening content stream 1/1...
DEBUG: Opened stream 1, resmap[0]=(nil)
DEBUG: cupsColorSpace=18
DEBUG: cupsBitsPerColor=8
DEBUG: cupsBitsPerPixel=8
DEBUG: cupsNumColors=1
DEBUG: cupsWidth=2480
DEBUG: cupsHeight=3507
ATTR: job-impressions=1
ATTR: job-pages=1
ATTR: job-media-sheets=1
DEBUG: cupsPageSize=[595.276 841.89]
DEBUG: Using Xpdf version of pdftoppm.
DEBUG: Running "pdftoppm -gray -aa no -r 300 '/tmp/c2993ef3.pdf' -".
Syntax Warning (198): Unknown compression method [cmf1:0x0a 78] in flate stream
DEBUG: 'P5'
DEBUG: '[2480 3508](tel:2480 3508)'
DEBUG: '255'
DEBUG: width=2480, height=3508, bpp=1, ystart=0, yend=3507
ATTR: job-impressions-completed=1
ATTR: job-media-sheets-completed=1
 ```
 
```
ippprint.conf:
<…>
Command ipptransform
OutputFormat application/vnd.hp-pcl
DeviceURI socket://127.0.0.1:9100         
 
```
 
By the way:
`DeviceURI [file://<jobname>.prn](file://%3cjobname%3e.prn)` would be nice for testing but as far as I remember it’s not working.
The function `httpSeparateURI()`, which is is used to parse the URI was terminated with error „Invalid hostname“.
„`file:/<jobname>`“ worked better but there is still some more work necessary…

[1-img-20230421-wa0001_jpg.pdf](https://github.com/istopwg/ippsample/files/12755828/1-img-20230421-wa0001_jpg.pdf)

Sorry PCL files are missing because the were not accepted. 
Not as .pcl and not as .zip.

**Comment by michaelrsweet** [comment]
So I made one fix to ipptransform that could have affected the rendering of the content - the dither matrix used by the PCL code didn't always get initialized so it is possible that affected you.

Anyways, even using CoreGraphics on macOS I get a blank page with your sample file - investigating.

WRT `file` URLs, you need three slashes before the filename, e.g. `file:///path/to/some/file`, since the hostname portion is empty but you still need it.

**Comment by AFischer4** [comment]
With the new version from September you only need additional changes to `xpdf` to analyze and correct the output of the example image above.
[embedded_stream_with_CR_LF.diff.txt.patch](https://github.com/istopwg/ippsample/files/12776980/embedded_stream_with_CR_LF.diff.txt.patch)

**Comment by michaelrsweet** [comment]
OK, so that would be a PDFio issue that you previously reported against *that* project. I'll close this issue out and work to get the PDFio fix incorporated...
