### ISSUE TITLE
IPP options with ‘-‘  in the name ignored, when passed to ipptransform

### ISSUE THREAD

**Issue by AFischer4** [istopwg/ippsample#282]
Calling `ipptool -v -T 3 ipp://<IPPHost>:8000/ipp/print/<MyPrinter> -f <sample>.pdf ex-print-job.test`
 fails to propagate IPP options with ‘-‘  in the name to `ipptransform`.

For example `ATTR enum print-quality 5` in ex-print-job.test will be passed to `ipptransform` as environment variable `IPP_PRINT_QUALITY=high` but the function get_option() in `ipptransform` does not find the option, because it  is looking first for a non existing command line option “`print-quality`” then for an environment variable “`IPP_PRINT-QUALITY`” and then for “`IPP_PRINT-QUALITY_DEFAULT`”.

The algorithm in `get_option()` to build the name of the environment variable must be the same, as in `serverTransformJob()`.
At the moment the replacement of ‘-‘ to ‘_’ is missing in `get_options()`!

Without correction,  `ipptransform` will ignore  a lot of options set by environment variables, because the initialization in `ippOptionsNew()` / `get_option()` is looking for the wrong names.
i
**Screenshots**

I used ippsample "v2023.03" for the tests.

**Comment by michaelrsweet** [comment]
[master e895c10] Fix handling of attributes with dashes in the name (Issue #282)
