### ISSUE TITLE
[Question] how can we host other printers on the ippserver ?

### ISSUE THREAD

**Issue by vitoo** [istopwg/ippsample#286]
Hello,

Sorry if theses are a dumb questions

I could read on the readme : "allows you to host shared printers"

Can we share a real printer (available on the local network) on the ippserver ? 
The ippserver need the IPP url of the real printer to connect ? Or there are othey way ? 
Is this the DeviceURI parameter in the .conf file ?

Thanks for your help

**Comment by michaelrsweet** [comment]
So for starters ippserver (and the ippsample project) provides a prototype implementation of various IPP specifications. It isn't intended for production use...

That said, there is very limited support for "hosting" PCL, PostScript, and IPP Everywhere printers by using the ipptransform command. The DeviceURI parameter can specify IPP (ipp://...), IPPS (ipps://...), and JetDirect (socket://...) network printers, and the OutputFormat parameter can be "application/vnd.hp-pcl", "application/postscript", "application/pdf", "image/pwg-raster", and/or "image/urf".
