### ISSUE TITLE
Document format/structure correctness tool ("ippdoclint")

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#29]
We ought to have a tool that can take an input PWG Raster document file and check its structure and report any errors / warnings / issues with the document's structure or content.

This could be used by an "ippserver" tool as a "command" to process the input files, which could then report on structural problems with the document content submitted with a Job, and report its status accordingly.

**Comment by michaelrsweet** [comment]
Let's try to tackle this for 1.0...

**Comment by michaelrsweet** [comment]
Re-titled this to track what we want to do:

- [ ] Support running standalone and as a print command program for ippserver, returning a non-zero exit code on error.
- [ ] Support PWG Raster, CUPS Raster, and Apple Raster files (via CUPS library)
- [ ] Support JPEG files (via JPEG library and/or ImageIO)
- [ ] Support PDF files (via MuPDF and/or CoreGraphics)
- [ ] Report as many possible format errors as we can.
- [ ] Support copies, print-color-mode, and sides (for counters)
- [ ] Report all of the job-impressions-xxx, job-media-sheets-xxx, and job-pages-xxx Job Status attributes.
- [ ] Report the document-format-error and document-unprintable-error "job-state-reasons" state keywords as appropriate.

**Comment by michaelrsweet** [comment]
Merging changes from PR #161...

**Comment by michaelrsweet** [comment]
OK, the initial version is done. We'll want to expand the PDF support to report color/monochrome pages in the future, but this bug can be closed.
