### ISSUE TITLE
ipptool: EXPECT directive uses case-sensitive host name comparison but should be case insensitive

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#36]
If an ipptool file has an expect directive in it looking at URIs, and the hostname of the Printer from its SRV record (discovered via ippfind) is using different capitalization than in the URIs reported by the Printer, ipptool will fail the expectations, even though DNS hostnames are supposed to be case-insensitive.

Example ipptool output:

    I-9. Get-Printer-Attributes Operation (default)                      [FAIL]
        RECEIVED: 15678 bytes in response
        status-code = successful-ok (successful-ok)
        EXPECTED: printer-icons WITH-ALL-VALUES "HP40B034762169.local"
        GOT: printer-icons="http://hp40b034762169.local/images/printer-small.png"
        GOT: printer-icons="http://hp40b034762169.local/images/printer.png"
        GOT: printer-icons="http://hp40b034762169.local/images/printer-large.png"
        EXPECTED: printer-supply-info-uri WITH-VALUE "HP40B034762169.local"
        GOT: printer-supply-info-uri="http://hp40b034762169.local/#hId-pgInkConsumables"

Regardless of the distastefulness of the hostname or the oddness that the Printer is reporting its hostname with one capitalization in one context and another capitalization in another context, this should not be failing because ipptool should be comparing the hostname portion of a URI in a case-insensitive manner.

**Comment by michaelrsweet** [comment]
I thought I had made a change to ipptool for this in the original 1.0 tools release...

**Comment by michaelrsweet** [comment]
OK, the last change was for stripping the trailing dot from the hostname as needed, not for case-insensitive comparisons.  I've pushed a more complete fix for the URI comparison problem to Github, please try it out and let me know if you have any problems...

[master a05997b] Fix comparisons of URIs so the right parts are case-insensitive (Issue #36)

**Comment by wifiprintguy** [comment]
Something isn't right here. I have compared the state of the ipptool output from the last IPP Everywhere Self Certification toolset with master, and the textual output is broken. The problem seems to have originated from the 947cefe8a21f022ae2ba1d46b37338379c520803 change set . If I go back to the 2e6d95a763a0559ebbbf87ceebee009bc846eaca change set, the output of "ipptool -vt ..." is what I would expect. After 947cefe8a21f022ae2ba1d46b37338379c520803, it gets all messed up, and that obfuscates the other underlying problem, which seems to be that the processing of WITH-ALL-HOSTNAMES, like in a line such as this (taken from ipp-tests.test) :

        	EXPECT printer-icons OF-TYPE uri WITH-ALL-HOSTNAMES "$hostname"

gets processed and output like so:

	Serenity: ippsample [658]$ ./tools/ipptool -vtP "_Smitty Palermo Hi_ I-9 Test Results $(datecodelong).plist" -I 'ipp://smitty-palermo-hi.local/ipp/print' test-i9-trimmed-2.test
	"test-i9-trimmed-2.test":
	I-9. Get-Printer-Attributes Operation to smitty-palermo-hi.localGet-Printer-Attributesattributes-charsetutf-8attributes-natural-languageenprinter-uriipp://smitty-palermo-hi.local:631/ipp/printrequesting-user-namesmittyrequested-attributesprinter-icons    Get-Printer-Attributes:
			attributes-charset (charset) = utf-8
			attributes-natural-language (naturalLanguage) = en
			printer-uri (uri) = ipp://smitty-palermo-hi.local:631/ipp/print
			requesting-user-name (nameWithoutLanguage) = smitty
			requested-attributes (keyword) = printer-icons
		I-9. Get-Printer-Attributes Operation to smitty-palermo-hi.local     [successful-okattributes-charsetutf-8attributes-natural-languageenprinter-iconshttp://smitty-palermo-hi.local/images/printer-small.pnghttp://smitty-palermo-hi.local/images/printer.pnghttp://smitty-palermo-hi.local/images/printer-large.pngFAIL]
			RECEIVED: 260 bytes in response
			status-code = successful-ok (successful-ok)
			attributes-charset (charset) = utf-8
			attributes-natural-language (naturalLanguage) = en
			printer-icons (1setOf uri) = http://smitty-palermo-hi.local/images/printer-small.png,http://smitty-palermo-hi.local/images/printer.png,http://smitty-palermo-hi.local/images/printer-large.png
	EXPECTED: printer-icons WITH-ALL-VALUES "smitty-palermo-hi.local"GOT: printer-icons="http://smitty-palermo-hi.local/images/printer-small.png"GOT: printer-icons="http://smitty-palermo-hi.local/images/printer.png"GOT: printer-icons="http://smitty-palermo-hi.local/images/printer-large.png"        EXPECTED: printer-icons WITH-ALL-VALUES "smitty-palermo-hi.local"
			GOT: printer-icons="http://smitty-palermo-hi.local/images/printer-small.png"
			GOT: printer-icons="http://smitty-palermo-hi.local/images/printer.png"
			GOT: printer-icons="http://smitty-palermo-hi.local/images/printer-large.png"

If I checkout change set 2e6d95a763a0559ebbbf87ceebee009bc846eaca and rerun my .test file (attached) the output is what I would expect, and doesn't fail the URIs at all:

	Serenity: ippsample [663]$ ./tools/ipptool -vtP "_Smitty Palermo Hi_ I-9 Test Results $(datecodelong).plist" -I 'ipp://smitty-palermo-hi.local/ipp/print' test-i9-trimmed-2.test.txt 
	"test-i9-trimmed-2.test.txt":
		Get-Printer-Attributes:
			attributes-charset (charset) = utf-8
			attributes-natural-language (naturalLanguage) = en
			printer-uri (uri) = ipp://smitty-palermo-hi.local:631/ipp/print
			requesting-user-name (nameWithoutLanguage) = smitty
			requested-attributes (keyword) = printer-icons
		I-9. Get-Printer-Attributes Operation to smitty-palermo-hi.local     [PASS]
			RECEIVED: 260 bytes in response
			status-code = successful-ok (successful-ok)
			attributes-charset (charset) = utf-8
			attributes-natural-language (naturalLanguage) = en
			printer-icons (1setOf uri) = http://smitty-palermo-hi.local/images/printer-small.png,http://smitty-palermo-hi.local/images/printer.png,http://smitty-palermo-hi.local/images/printer-large.png
[test-i9-trimmed-2.test.txt](https://github.com/istopwg/ippsample/files/1136861/test-i9-trimmed-2.test.txt)

So I really don't know what is going on here...but I think we need to get this straightened out.

**Comment by wifiprintguy** [comment]
OK - textual problems were reported separately in issue #46, which has been resolved. We still need to complete the case-insensitive comparison of hostnames for WITH-ALL-HOSTNAMES. More very soon...

**Comment by wifiprintguy** [comment]
Created pull request #47 to hopefully resolve this issue

**Comment by wifiprintguy** [comment]
And updated the branch in pull request #47 to also add support for WITH-RESOURCE, WITH-ALL-RESOURCES, WITH-SCHEME and WITH-ALL-SCHEMES, and also fix proper reporting of issues with all these EXPECT directives.

**Comment by michaelrsweet** [comment]
OK, compare_uris was doing the right thing, but it wasn't getting the full URI, just the component. Changed the implementation a bit to handle WITH-xxx more consistently for all attribute types.

**Comment by wifiprintguy** [comment]
Seems to work properly - thanks for the fix!
