### ISSUE TITLE
ipptool doesn't support sending out-of-band values in requests in tests, but should

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#37]
We encountered an error when trying to create an ipptool .test file that contained the following directive for the request:

    ATTR no-value finishings-col fakeval
    # or
    ATTR no-value finishings-col

The ipptool tool currently doesn't support this, but it should, so that these out-of-band values that are legitimate can be sent in requests for testing purposes.

**Comment by michaelrsweet** [comment]
[master aff4019] Add support for out-of-band attributes (Issue #37)

**Comment by michaelrsweet** [comment]
Syntax is:

    ATTR out-of-band-tag attribute-name

and:

    MEMBER out-of-band-tag member-name
