### ISSUE TITLE
ipptool: DELAY directive should be applied to each retry

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#38]
If you have an ipptool test file like so:

{
   DELAY 2

   NAME "Get printer-uuid using an IPP Get-Printer-Attributes operation"

   OPERATION Get-Printer-Attributes
   Version 2.0

   GROUP operation
   ATTR charset attributes-charset utf-8
   ATTR language attributes-natural-language en
   ATTR uri printer-uri $uri
   ATTR keyword requested-attributes printer-uuid

   STATUS successful-ok

   EXPECT printer-fake-attribute REPEAT-NO-MATCH REPEAT-LIMIT 10

}

I am seeing a 10 repeat limit and a DELAY of 2 seconds. So would that mean it would take:

1. 2 seconds for delay + 11 tries as fast as it could go (first try + 10 retries)
2. 11 tries, each with a 2 second delay
3. 10 tries, each with a 2 second delay
4. Something else?

It is my belief that it should be #2.

**Comment by michaelrsweet** [comment]
OK, so the existing code uses a semi-random delay between repeats (a fibonacci sequence: 1 1 2 3 5 8). What I've done is change this to use a default repeat interval (delay) of 5 seconds, which is overridden by the DELAY directive. The DELAY directive now also allows you to specify two numbers to control the initial delay and the repeat interval separately, e.g.:

    DELAY 30,10

specifies an initial delay of 30 seconds and 10 seconds between repeated tests.

[master f292e13] Update DELAY directive to control repeat interval (Issue #38)

**Comment by michaelrsweet** [comment]
(this will get mirrored to the ippeveselfcert repository as soon as I finish up the CUPS 2.2.4 changes, which will get mirrored to ippsample and ippeveselfcert...)
