### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by daryl-williams** [istopwg/ippsample#4]
Hi. I'm not sure if this is the appropriate place to ask for help, but I haven't found any place else. Hope you will be patient. I am trying to build your software on a CentOS 7.2 host and getting the following error (among other warnings):

cc1: error: unrecognized command line option "-Wno-tautological-compare" [-Werror]
cc1: all warnings being treated as errors
make[1]: *** [printer.o] Error 1

I am wondering if there are any instructions or any other kind of help to get this built?

Thanks for your time.

Regards,

Daryl

**Comment by michaelrsweet** [comment]
This is fine for reporting build problems - can you provide the complete build log? The "-Wno-tautological-compare" bit is a GCCism (no way to make the configure check work...) but is hiding the real build issue.

**Comment by daryl-williams** [comment]
Thanks for your reply. I tweaked the Makedefs file a bit got past the 
initial problem. There was another problem but I got past that by 
installing the avahi development packages avahi-devel.x86_64 and 
avahi-glib-devel.x86_64. I then restoredthe  Makedefs file to the 
original and I am now getting the error below. If I can provide any 
further information please let me know. This is occurring on a centos 
system (CentOS Linux release 7.2.1511 (Core)) but I also ran into 
similar issues on Ubuntu 14.04.

$ make
Making all in cups...
Making all in proxy...
Making all in server...
Compiling client.c...
In file included from client.c:15:
./ippserver.h:79:24: error: redefinition of typedef '_cups_cond_t' is a 
C11 feature [-Werror,-Wtypedef-redefinition]
typedef pthread_cond_t _cups_cond_t;
                        ^
../cups/thread-private.h:38:24: note: previous definition is here
typedef pthread_cond_t _cups_cond_t;
                        ^
1 error generated.
make[1]: *** [client.o] Error 1
make: *** [all] Error 1


Following is the full log after a make clean:


make
Making all in cups...
Compiling array.c...
Compiling auth.c...
Compiling debug.c...
Compiling dest.c...
Compiling dest-job.c...
Compiling dest-localization.c...
Compiling dest-options.c...
Compiling dir.c...
Compiling encode.c...
Compiling error.c...
Compiling file.c...
Compiling getputfile.c...
Compiling globals.c...
Compiling hash.c...
Compiling http.c...
Compiling http-addr.c...
Compiling http-addrlist.c...
Compiling http-support.c...
Compiling ipp.c...
Compiling ipp-support.c...
Compiling langprintf.c...
Compiling language.c...
Compiling md5.c...
Compiling md5passwd.c...
Compiling notify.c...
Compiling options.c...
Compiling pwg-media.c...
Compiling raster.c...
Compiling request.c...
Compiling snprintf.c...
Compiling string.c...
Compiling tempfile.c...
Compiling thread.c...
Compiling tls.c...
Compiling transcode.c...
Compiling usersys.c...
Compiling util.c...
Archiving libcups.a...
a - array.o
a - auth.o
a - debug.o
a - dest.o
a - dest-job.o
a - dest-localization.o

a - dest-options.o
a - dir.o
a - encode.o
a - error.o
a - file.o
a - getputfile.o
a - globals.o
a - hash.o
a - http.o
a - http-addr.o
a - http-addrlist.o
a - http-support.o
a - ipp.o
a - ipp-support.o
a - langprintf.o
a - language.o
a - md5.o
a - md5passwd.o
a - notify.o
a - options.o
a - pwg-media.o
a - raster.o
a - request.o
a - snprintf.o
a - string.o
a - tempfile.o
a - thread.o
a - tls.o
a - transcode.o
a - usersys.o
a - util.o
Making all in proxy...
Compiling ippproxy.c...
Linking ippproxy...
Making all in server...
Compiling client.c...
In file included from client.c:15:
./ippserver.h:79:24: error: redefinition of typedef '_cups_cond_t' is a 
C11 feature [-Werror,-Wtypedef-redefinition]
typedef pthread_cond_t _cups_cond_t;
                        ^
../cups/thread-private.h:38:24: note: previous definition is here
typedef pthread_cond_t _cups_cond_t;
                        ^
1 error generated.
make[1]: *** [client.o] Error 1
make: *** [all] Error 1

**Comment by michaelrsweet** [comment]
[master e91a440] Fix conditional definitions, which are now in thread-private.h

**Comment by daryl-williams** [comment]
Hi Michael,

Thanks for the quick fix, I got the new version and it built without a 
problem. Although when I did a make install the install script 
complained that ipptransform did not exist:

# make install
Installing in cups...
Installing in proxy...
Installing in server...
Installing in tools...
install: ipptransform does not exist
make[1]: *** [install] Error 1
make: *** [install] Error 1

I then changed to the tools directory and tried to build ipptransform 
but it failed with too many errors emitted. I'm not sure how important 
this is, but I wanted to let you know.

Thanks again,

Daryl

**Comment by michaelrsweet** [comment]
Ah, we need to make installing ipptransform conditional, just as we do for building it - you need (a recent versions of) MuPDF installed to build it on Linux...

**Comment by michaelrsweet** [comment]
[master bcea634] Fix installs when ipptransform isn't built

**Comment by daryl-williams** [comment]
Thanks Michael, I just downloaded and built mupdf. It installed mutool 
and mujstest, libmupdf.a and libmupdfthird.a but I am unable to find a 
mupdf binary although there is a man page for it. After installing mupdf 
I went back into the ippsample/tools/ directory and tried building 
ipptransform but it error-ed out again.

**Comment by michaelrsweet** [comment]
Make sure the MuPDF headers got installed, and re-run configure to get the updated build settings. There isn't a mupdf binary specifically...

(FWIW, ipptransform just allows you to convert and print PDF and JPEG files to PCL and PWG Raster printers...)

**Comment by daryl-williams** [comment]
Did a make clean and reconfigured then ran make and got the following error:

Compiling ipptransform.c...
ipptransform.c:2081:86: error: too few arguments to function call, 
expected 5, have 4
   pixmap = fz_new_pixmap(context, cs, (int)ras.header.cupsWidth, 
(int)ras.band_height);
~~~~~~~~~~~~~ ^
/usr/local/include/mupdf/fitz/pixmap.h:51:1: note: 'fz_new_pixmap' 
declared here
fz_pixmap *fz_new_pixmap(fz_context *ctx, fz_colorspace *cs, int w, int 
h, int alpha);
^
1 error generated.
make[1]: *** [ipptransform.o] Error 1
make: *** [all] Error 1

Also I checked and the mupdf headers are installed in /usr/local/include.



On 6/14/16 12:09 PM, Michael R Sweet wrote:
>
> Make sure the MuPDF headers got installed, and re-run configure to get 
> the updated build settings. There isn't a mupdf binary specifically...
>
> (FWIW, ipptransform just allows you to convert and print PDF and JPEG 
> files to PCL and PWG Raster printers...)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/istopwg/ippsample/issues/4#issuecomment-225985164>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AA_wdeupCldX9u_4Qb1Tg2cNK7uGUQdIks5qLvxpgaJpZM4I0xFs>.
>

**Comment by michaelrsweet** [comment]
What version of MuPDF are you using?

**Comment by daryl-williams** [comment]
I believe it's version 1.9. I cloned it from their repo with:

git clone --recursive git://git.ghostscript.com/mupdf.git

and mutool -v yields: mutool version 1.9a.

**Comment by michaelrsweet** [comment]
OK, it must be some intermediate version after 1.9a, because the fz_new_pixmap in the 1.9a release does NOT have an alpha parameter...

(API stability has not been a strong point in MuPDF...)

**Comment by michaelrsweet** [comment]
Confirmed, the git repo is different than 1.9a. For now I would recommend sticking with a released version of MuPDF. I'm off to file a request that they stabilize the APIs so we can depend on things not to change radically... :/

**Comment by daryl-williams** [comment]
I got the 1.9a tarball built and installed it, did a make clean, 
re-configured and built ippsample without any problems, including 
ipptransform. I really appreciate all your help. Thanks again.

Regards,

Daryl

**Comment by michaelrsweet** [comment]
No problem!
