### ISSUE TITLE
ippserver: support multiple concurrent DNS-SD service subtypes by allowing multiple "-r" options

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#40]
It would be beneficial if ippserver could support accepting multiple "-r" options so that it could advertise more than one DNS-SD service subtype at a time.

**Comment by michaelrsweet** [comment]
At least with mDNSResponder, you can list multiple subtypes, e.g.:

    -r _print,_universal

Right now the Avahi code doesn't support multiple subtypes (like the cupsd code already does), so I'll use this bug to a) add it and b) document it...
