### ISSUE TITLE
ippserver: error reported in config file specifies wrong line number in some cases

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#43]
When there is an error in an ippserver configuration file, ippserver in some cases reports the wrong line number, which makes it difficult to fix the issue.

Attached is a ".conf" file that declares a number of "vendor-specific" attributes to exercise the attribute definition parsing, and if you selectively comment out portions of that, you observe the number reporting starts to go off in the weeds where a collection is defined. (I had to give it a .txt file extension to make attaching to Github happy...)

[ippserver-data-type-test.conf.txt](https://github.com/istopwg/ippsample/files/1247116/ippserver-data-type-test.conf.txt)

**Comment by wifiprintguy** [comment]
From running in a debugger, It seems that the "(*linenum) ++;" on line 1182

https://github.com/istopwg/ippsample/blob/26956bfe294073338a94ee04038bbf106ef04b83/server/conf.c#L1182

ought to actually be replaced with something like:

                // go back 1 char so that the '\n' is handled the next time through
                // to preserve the correct line number for the returned token
                cupsFileSeek(fp, cupsFileTell(fp) - 1);

The processing of collections, specifically an attribute that is 1setOf collection, also causes the introduction of some line number skew / inaccuracy.

**Comment by wifiprintguy** [comment]
Hmm maybe found the other problem area. The "cupsFileSeek(fp, pos);" call rewinds the file pointer but doesn't restore the line number:

https://github.com/istopwg/ippsample/blob/26956bfe294073338a94ee04038bbf106ef04b83/server/conf.c#L442

**Comment by wifiprintguy** [comment]
working on a patch - pull request pending...

**Comment by michaelrsweet** [comment]
[master 31d76d5] Fix reporting of line numbers in conf files (Issue #44)
