### ISSUE TITLE
ipptool: unable to EXPECT a collection member IN-GROUP

### ISSUE THREAD

**Issue by brendenlarson** [istopwg/ippsample#45]
[in-group.test.txt](https://github.com/istopwg/ippsample/files/1264867/in-group.test.txt)

As part of an EXPECT directive, ipptool cannot locate collection members when using the IN-GROUP predicate.
To EXPECT a collection member, the collection/member syntax is used. This works fine unless you also specify IN-GROUP.
Even though a WireShark capture shows the desired member is in the proper group, when using the collection/member syntax with IN-GROUP the EXPECT fails with error "got zero."

See in-group.test.txt for an example ipptoolfile that illustrates this behavior.

**Comment by michaelrsweet** [comment]
The workaround is to EXPECT the collection attribute in the specified group, and then just EXPECT the collection/member attribute separately. I'll investigate how easily we could add support for looking at the parent attribute's group (but I think we don't have a parent pointer...)

**Comment by brendenlarson** [comment]
Thanks, that work around will work for me!

**Comment by michaelrsweet** [comment]
OK, there is no parent pointer so I think the solution is to look at the parent attribute (EXPECT parent/member IN-GROUP should check the parent attribute's group membership).

**Comment by michaelrsweet** [comment]
[master 73bc40b] Support "EXPECT foo/bar IN-GROUP group" (Issue #45)
