### ISSUE TITLE
ippserver : When "printer-resolution" in Validate-Job operation request, response is 'client-error-attributes-or-values-not-supported'

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#49]
When a "Validate-Job" operation is sent including a "printer-resolution" attribute with the value set from "printer-resolution-default", the Printer provided by ippserver will respond with status-code = client-error-attributes-or-values-not-supported (Unsupported printer-resolution resolution value.)

Attached is a test file that illustrates this. You can demonstrate the problem like so:

./ippfind -n foo -x ./ipptool -vt 'ipp://Serenity.local:8503/ipp/print/foo' ipp-test-I11.test \;

[ipp-test-I11.test.txt](https://github.com/istopwg/ippsample/files/1282080/ipp-test-I11.test.txt)

**Comment by michaelrsweet** [comment]
I guess the question is whether the printer-resolution-supported attribute includes the printer-resolution-default value...

**Comment by wifiprintguy** [comment]
Yep - ippserver reports:

        printer-resolution-default (resolution) = 600dpi
        printer-resolution-supported (resolution) = 600dpi

The failure was first observed when running the IPP Everywhere Self Certification test suite against the ippsample ippserver implementation (I have .conf files for "basic" and "PDF" IPP Everywhere implementations that I will post soon).

**Comment by wifiprintguy** [comment]
Fiddling with the code on master, I found that if I changed "client->printer->dev_attrs" to "client->printer->attrs" on this line, the operation succeeds:

https://github.com/istopwg/ippsample/blob/8d66797c7f6cdb1a573956b6b11ea9c641be584f/server/ipp.c#L3831

In the debugger, "client->printer->dev_attrs" is NULL but "client->printer->attrs" points to something valid.

**Comment by michaelrsweet** [comment]
OK, we need to resolve this differently - the dev_attrs holds the INFRA device attributes...  Basically we need to look at the union of printer->attrs and printer->dev_attrs.

**Comment by michaelrsweet** [comment]
[master 088f8fe] Fix job attribute validation (Issue #49, Issue #59)
