### ISSUE TITLE
How to define more than one printer to ippserver?

### ISSUE THREAD

**Issue by daryl-williams** [istopwg/ippsample#5]
Hi, I have successfully been able to print using ippserver but  when I use the -C /some/config/dir flag to point ippserver to a config directory it does not configure any printers. I am using a standard cups config directory with two printers defined in printers.conf. The ippserver appears to start just fine and with the verbose flag on it prints:

$ ./start-ippserver.sh
Using default spool directory "/home/daryl/ippserver".
Ignore Avahi state 2.
Using default listeners for demo.cirrusprint.com:631.
serverRun: 0 printers configured.
serverRun: 1 listeners configured.

I start the ippserver with the following command line:

/usr/bin/sudo /usr/local/sbin/ippserver -d /home/daryl/ippserver -k -p 631 -vv -C /tmp/cups.d

An interesting aside, using the -vv flag the verbosity level is much less than without the -C flag.
Any help would be appreciated, or if there are any docs I could read up on that would be great as well.

Regards,

Daryl Williams

**Comment by michaelrsweet** [comment]
Daryl,

ippserver doesn't use cupsd's configuration file syntax. I'm in the process of updating the ippserver man page to document it, but see the file DESIGN.md for some examples.

**Comment by daryl-williams** [comment]
Thanks Michael, looking at it now.

**Comment by daryl-williams** [comment]
Michael, I setup the config directory as specified in the DESIGN.md file 
and when I run ippserver it goes into verbose mode by itself and exits 
with a status code of 139. Following is the command line I used and part 
of the output produced by ippserver:

$ /usr/bin/sudo /usr/local/sbin/ippserver -d 
/home/daryl/ippserver/queues -k -p 631 -C /home/daryl/ippserver/config

Using default spool directory "/home/daryl/ippserver/queues".
Ignore Avahi state 2.
Using default listeners for demo.cirrusprint.com:631.
Loading printers from "/home/daryl/ippserver/config/print".
Loading printer from "ipp-printer.conf".
serverCreatePrinter(resource="/ipp/print/ipp-printer", 
name="ipp-printer", location="(null)", make="(null)", model="(null)", 
icon="(null)", docformats="(null)", ppm=0, ppm_color=0, duplex=0, pin=0, 
attrs=0x14ae730, command="(null)", 
device_uri="ipp://demo.cirrusprint.com/ipp/print", proxy_user="(null)")
[Printer ipp-printer] printer-more-info="http://demo.cirrusprint.com:631/"
[Printer ipp-printer] 
printer-supply-info-uri="http://demo.cirrusprint.com:631/supplies"
[Printer ipp-printer] 
printer-uri="ipp://demo.cirrusprint.com:631/ipp/print/ipp-printer"
[Printer ipp-printer] version=2.0

My config directory has a system.conf copied from DESIGN.md:

DefaultPrinter ipp-printer
LogLevel debug
LogFile stderr

amd the print directory has the file ipp-printer.conf:

DeviceURI ipp://demo.cirrusprint.com/ipp/print
#Attr collection media-col-ready {media-size={x-dimension=21590 
y-dimension=27940}},{media-size={x-dimension=21000 y-dimension=29700}}
#Attr keyword media-ready na_letter_8.5x11in,iso_a4_210x297mm

Hope this is useful and that I'm not making some stupid mistake, but ya 
never know... ;)

**Comment by michaelrsweet** [comment]
Status 139 would be a segfault - can you run ippserver inside gdb and get a backtrace?

**Comment by daryl-williams** [comment]
Here you go:

# gdb ippserver
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later 
<http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/sbin/ippserver...done.
(gdb) run ippserver -d /home/daryl/ippserver/queues -k -p 631 -C 
/home/daryl/ippserver/config
Starting program: /usr/local/sbin/ippserver ippserver -d 
/home/daryl/ippserver/queues -k -p 631 -C /home/daryl/ippserver/config
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Using default spool directory "/home/daryl/ippserver/queues".
Ignore Avahi state 2.
[New Thread 0x7ffff6872700 (LWP 647)]
Using default listeners for demo.cirrusprint.com:631.
Loading printers from "/home/daryl/ippserver/config/print".
Loading printer from "foo.conf".
serverCreatePrinter(resource="/ipp/print/foo", name="foo", 
location="(null)", make="(null)", model="(null)", icon="(null)", 
docformats="(null)", ppm=0, ppm_color=0, duplex=0, pin=0, 
attrs=0x675730, command="(null)", 
device_uri="ipp://demo.cirrusprint.com/ipp/print", proxy_user="(null)")
[Printer foo] printer-more-info="http://demo.cirrusprint.com:631/"
[Printer foo] 
printer-supply-info-uri="http://demo.cirrusprint.com:631/supplies"
[Printer foo] printer-uri="ipp://demo.cirrusprint.com:631/ipp/print/foo"
[Printer foo] version=2.0
[Printer foo] request-id=0
[Printer foo] printer-attributes-tag
[Printer foo] charset-configured (charset) utf-8
[Printer foo] charset-supported (1setOf charset) us-ascii,utf-8
[Printer foo] color-supported (boolean) false
[Printer foo] compression-supported (1setOf keyword) deflate,gzip,none
[Printer foo] copies-default (integer) 1
[Printer foo] copies-supported (rangeOfInteger) 1-999
[Printer foo] document-format-default (mimeMediaType)
[Printer foo] document-password-supported (integer) 127
[Printer foo] finishings-default (enum) none
[Printer foo] finishings-supported (enum) none
[Printer foo] generated-natural-language-supported (naturalLanguage) en
[Printer foo] identify-actions-default (keyword) sound
[Printer foo] identify-actions-supported (1setOf keyword) display,sound
[Printer foo] ipp-features-supported (1setOf keyword) 
document-object,ipp-everywhere,infrastructure-printer,page-overrides
[Printer foo] ipp-versions-supported (1setOf keyword) 1.0,1.1,2.0
[Printer foo] ippget-event-life (integer) 300
[Printer foo] job-account-id-default (nameWithoutLanguage)
[Printer foo] job-account-id-supported (boolean) true
[Printer foo] job-accounting-user-id-default (nameWithoutLanguage)
[Printer foo] job-accounting-user-id-supported (boolean) true
[Printer foo] job-creation-attributes-supported (1setOf keyword) 
copies,ipp-attribute-fidelity,job-account-id,job-accounting-user-id,job-name,job-password,job-priority,media,media-col,multiple-document-handling,orientation-requested,print-quality,sides
[Printer foo] job-ids-supported (boolean) true
[Printer foo] job-k-octets-supported (rangeOfInteger) 0-81262592
[Printer foo] job-password-supported (integer) 4
[Printer foo] job-priority-default (integer) 50
[Printer foo] job-priority-supported (integer) 100
[Printer foo] job-sheets-default (nameWithoutLanguage) none
[Printer foo] job-sheets-supported (nameWithoutLanguage) none
[Printer foo] media-bottom-margin-supported (integer) 635
[Printer foo] media-col-database (1setOf collection) 
{media-key=na_letter_8.5x11in media-size={x-dimension=21590 
y-dimension=27940} media-size-name=na_letter_8.5x11in 
media-bottom-margin=635 media-left-margin=635 media-right-margin=635 
media-top-margin=635},{media-key=na_legal_8.5x14in 
media-size={x-dimension=21590 y-dimension=35560} 
media-size-name=na_legal_8.5x14in media-bottom-margin=635 
media-left-margin=635 media-right-margin=635 
media-top-margin=635},{media-key=iso_a4_210x297mm 
media-size={x-dimension=21000 y-dimension=29700} 
media-size-name=iso_a4_210x297mm media-bottom-margin=635 
media-left-margin=635 media-right-margin=635 media-top-margin=635}
[Printer foo] media-col-default (collection) 
{media-key=na_letter_8.5x11in media-size={x-dimension=21590 
y-dimension=27940} media-size-name=na_letter_8.5x11in 
media-bottom-margin=635 media-left-margin=635 media-right-margin=635 
media-top-margin=635}
[Printer foo] media-col-ready (collection) {media-key=na_letter_8.5x11in 
media-size={x-dimension=21590 y-dimension=27940} 
media-size-name=na_letter_8.5x11in media-bottom-margin=635 
media-left-margin=635 media-right-margin=635 media-top-margin=635}
[Printer foo] media-default (keyword) na_letter_8.5x11in
[Printer foo] media-left-margin-supported (integer) 635
[Printer foo] media-ready (keyword) na_letter_8.5x11in
[Printer foo] media-right-margin-supported (integer) 635
[Printer foo] media-supported (1setOf keyword) 
na_letter_8.5x11in,na_legal_8.5x14in,iso_a4_210x297mm
[Printer foo] media-size-supported (1setOf collection) 
{x-dimension=21590 y-dimension=27940},{x-dimension=21590 
y-dimension=35560},{x-dimension=21000 y-dimension=29700}
[Printer foo] media-source-supported (keyword) face-down
[Printer foo] media-top-margin-supported (integer) 635
[Printer foo] media-type-supported (keyword) auto
[Printer foo] media-col-supported (1setOf keyword) 
media-bottom-margin,media-left-margin,media-right-margin,media-size,media-size-name,media-source,media-top-margin,media-type
[Printer foo] multiple-document-handling-supported (1setOf keyword) 
separate-documents-uncollated-copies,separate-documents-collated-copies
[Printer foo] multiple-document-jobs-supported (boolean) false
[Printer foo] multiple-operation-time-out (integer) 60
[Printer foo] multiple-operation-time-out-action (keyword) abort-job
[Printer foo] natural-language-configured (naturalLanguage) en
[Printer foo] notify-attributes-supported (1setOf keyword) 
printer-state-change-time,notify-lease-expiration-time,notify-subscriber-user-name
[Printer foo] notify-events-default (keyword) job-completed
[Printer foo] notify-events-supported (1setOf keyword) 
document-completed,document-config-changed,document-created,document-fetchable,document-state-changed,document-stopped,job-completed,job-config-changed,job-created,job-fetchable,job-progress,job-state-changed,job-stopped,printer-config-changed,printer-finishings-changed,printer-media-changed,printer-queue-order-changed,printer-restarted,printer-shutdown,printer-state-changed,printer-stopped
[Printer foo] notify-lease-duration-default (integer) 86400
[Printer foo] notify-lease-duration-supported (rangeOfInteger) 0-67108863
[Printer foo] notify-lease-duration-default (integer) 21
[Printer foo] notify-pull-method-supported (keyword) ippget
[Printer foo] number-up-default (integer) 1
[Printer foo] number-up-supported (integer) 1
[Printer foo] operations-supported (1setOf enum) 
Print-Job,Print-URI,Validate-Job,Create-Job,Send-Document,Send-URI,Cancel-Job,Get-Job-Attributes,Get-Jobs,Get-Printer-Attributes,Get-Printer-Supported-Values,Create-Printer-Subscriptions,Create-Job-Subscriptions,Get-Subscription-Attributes,Get-Subscriptions,Renew-Subscription,Cancel-Subscription,Get-Notifications,Get-Document-Attributes,Get-Documents,Cancel-My-Jobs,Close-Job,Identify-Printer,Validate-Document,0x003f,0x0040,0x0041,0x0042,0x0043,0x0044,0x0045,0x0047,0x0048,0x0049,0x0046
[Printer foo] orientation-requested-default (no-value) no-value
[Printer foo] orientation-requested-supported (1setOf enum) 
portrait,landscape,reverse-landscape,reverse-portrait
[Printer foo] output-bin-default (keyword) face-down
[Printer foo] output-bin-supported (keyword) face-down
[Printer foo] overrides-supported (1setOf keyword) document-number,pages
[Printer foo] page-ranges-supported (boolean) true
[Printer foo] pages-per-minute (integer) 0
[Printer foo] pdl-override-supported (keyword) attempted
[Printer foo] preferred-attributes-supported (boolean) false
[Printer foo] print-color-mode-default (keyword) auto
[Printer foo] print-color-mode-supported (1setOf keyword) 
auto,color,monochrome
[Printer foo] print-content-optimize-default (keyword) auto
[Printer foo] print-content-optimize-supported (keyword) auto
[Printer foo] print-rendering-intent-default (keyword) auto
[Printer foo] print-rendering-intent-supported (keyword) auto
[Printer foo] print-quality-default (enum) normal
[Printer foo] print-quality-supported (1setOf enum) draft,normal,high
[Printer foo] printer-device-id (textWithoutLanguage) 
MFG:(null);MDL:(null);;
[Printer foo] printer-get-attributes-supported (keyword) document-format
[Printer foo] printer-geo-location (unknown) unknown
[Printer foo] printer-is-accepting-jobs (boolean) true
[Printer foo] printer-info (textWithoutLanguage) foo
[Printer foo] printer-location (textWithoutLanguage)
[Printer foo] printer-make-and-model (textWithoutLanguage) (null) (null)
[Printer foo] printer-more-info (uri) http://demo.cirrusprint.com:631/
[Printer foo] printer-name (nameWithoutLanguage) foo
[Printer foo] printer-organization (textWithoutLanguage) Apple Inc.
[Printer foo] printer-organizational-unit (textWithoutLanguage) Printing 
Engineering
[Printer foo] printer-resolution-default (resolution) 600dpi
[Printer foo] printer-resolution-supported (resolution) 600dpi
[Printer foo] printer-supply-info-uri (uri) 
http://demo.cirrusprint.com:631/supplies
[Printer foo] printer-uri-supported (uri) 
ipp://demo.cirrusprint.com:631/ipp/print/foo
[Printer foo] printer-uuid (uri) 
urn:uuid:52ecbabf-5e10-38f1-7ef1-f4c7cb7cafa2
[Printer foo] reference-uri-schemes-supported (1setOf uriScheme) 
file,ftp,http
[Printer foo] sides-default (keyword) one-sided
[Printer foo] sides-supported (keyword) one-sided
[Printer foo] uri-authentication-supported (keyword) none
[Printer foo] uri-security-supported (keyword) none
[Printer foo] which-jobs-supported (1setOf keyword) 
completed,not-completed,aborted,all,canceled,pending,pending-held,processing,processing-stopped

Program received signal SIGSEGV, Segmentation fault.
0x000000000041a659 in register_printer (printer=0x67e100, location=0x0, 
make=0x0, model=0x0, formats=0x0, adminurl=0x7fffffffc730 
"http://demo.cirrusprint.com:631/",
     uuid=0x7fffffffbe39 "52ecbabf-5e10-38f1-7ef1-f4c7cb7cafa2", 
color=0, duplex=0, subtype=0x66e040 "_print") at printer.c:1529
1529      if (*location)
(gdb)


and please let me know what else I can do to help.

**Comment by michaelrsweet** [comment]
OK, had to copy over some fixes from the mDNSResponder code to the Avahi code.

[master c4e5f82] Fix crash (Issue #5)

**Comment by daryl-williams** [comment]
Thanks Michael, I pulled the changes and it is working now!
