### ISSUE TITLE
[Raspberry Pi 3] ippserver startup consumes 100% CPU and is slow or pausing -- initial lag sometimes more than 5 min before HTTP resources become available

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#52]
I'm testing *`ippserver`* functionality on a Raspberry Pi 3 running openSUSE v*Leap 42.3*. Compiled the current sources (latest commit was Oct 12, cc48390cfac77120de7c694e1f67fbd091d66717) on the Raspbi.

While the Raspbi on other occasions responds in a quite "snappy" way (I only log in via SSH and don't run any GUI stuff on it, though there's some installed), I find *`ippserver`* to be very hesitant in starting up.

I did first run it like this:

```
kp@raspi3:~/svn-stuff/git.ippsample>  server/ippserver -vvvv "Test Test"

 Using default configuration with a single printer.
 Using default data directory "/tmp/ippserver.5030".
 Using default spool directory "/tmp/ippserver.5030".
 Ignore Avahi state 2.
 Using default listeners for raspi3.local.:8000.
 serverCreatePrinter(resource="/ipp/print", name="Test Test", location="", make="Test", \
   model="Printer", icon="(null)", docformats="application/pdf,image/jpeg,image/pwg-raster", \
   ppm=0, ppm_color=0, duplex=0, pin=0, attrs=(nil), command="(null)", device_uri="(null)", \
   proxy_user="(null)", strings=(nil))
 Using ppm=0
 Using ppm_color=0
 [Printer Test Test] printer-more-info="http://raspi3.fritz.box:8000/ipp/print"
 [Printer Test Test] printer-supply-info-uri="http://raspi.local.:8000/ipp/print/supplies"
 [Printer Test Test] printer-uri="ipp://raspi3.local.:8000/ipp/print"
```

At this point the output pauses for quite a while. The mentioned URIs from the last three lines were not accessible, and after a timeout the browser displayed an error message.

Initially I thought it is all that is expected to happen. Then, while googling, I found other example outputs being quoted, which didn't look as disappointing as the above one....  :-)

I tried again. However, after the same output as above (which displays on the spot), I was called for dinner and left the terminal sitting there.

So I was surprised to find the screen propulated by all kinds of IPP messages returned from *`ippserver`*.

So I used the following modified command to measure the time for the process to complete its upstart, and repeated it five times:

```
kp@raspi3:~/svn-stuff/git.ippsample> server/ippserver -vvvv "Test Test" 2>&1 \
                                                     | tee ippserver-$(date +%H-%M-%S).log
```

Here are the resulting infos:

```
kp@raspi3:~/svn-stuff/git.ippsample> ls --full-time -gG ippserver-*.log | cut -c 19-

 2017-10-25 15:44:05.460235590 +0200 ippserver-15:42:59.log
 2017-10-25 15:49:31.887417751 +0200 ippserver-15:44:54.log
 2017-10-25 16:01:32.551159324 +0200 ippserver-15:57:34.log
 2017-10-25 16:12:28.565455783 +0200 ippserver-16:07:12.log
 2017-10-25 16:20:12.061432491 +0200 ippserver-16:17:19.log
```

As you can see, it took at least 66 seconds (file \*-15:42:59.log) and up to 316 seconds (file ˜*16:07:12.log) for ippserver to end its "pausing" after printing the first three *`[Printer Test Test]`*-lines on screen.

What is it doing in this time??  The following screenshot shows how *`htop`* reports 100% CPU usage during that time (several minutes, as shown above):

![`htop` reporting 100% CPU usage during several minutes of startup time for *`ippserver`* on Raspberry Pi 3](https://i.stack.imgur.com/lkqgJ.png)

After the startup time is over, and after the terminal has displayed all the ippserver's output, the CPU load reported by htop is back to normal:

![`htop` reporting 0% CPU usage after startup of *`ippserver`* on Raspberry Pi 3 is completed](https://i.stack.imgur.com/8fKUL.png)

If you watch the terminal "life" while running the commands and try to access one of the HTTP resources with a browser at the same time, you'll notice that the resource becomes available only after the terminal output has overcome the initial lag.

**Comment by michaelrsweet** [comment]
My guess is that ippserver is trying to create a self-signed TLS certificate; this *should* be saved for subsequent runs, however.

Can you attach the log files you refer to?

**Comment by KurtPfeifle** [comment]
I'll dig out the logs in a minute. However, I do not see any sign in the log about something like this going on. If it indeed is, that activity does not make it into the log.

Ok, here's the last file, which is a lill' longer then the ones quoted above since it contains some client connection activities too (web interface):
[ippserver-16:43:00.log.gz](https://github.com/istopwg/ippsample/files/1416371/ippserver-16.43.00.log.gz)

**Comment by KurtPfeifle** [comment]
I've made an additional test now: instead of the most simplest command as above, I tested the mode where *`ippserver`* reads its configuration files from a *"run"* subdirectory.

Also, I have 6 different printers defined in the *"print"* subdir through various *"\*.conf"* files (plus one in the *"print3d"* subdir).

The "pause" I described for the one default printer in my original description occurs for every additional printer which should get shown in the `-vvvv` startup output.

The web interface gets only show after the last printer is loaded. Before that, there is a several minutes long *"Waiting for raspi..."* message in the browser status bar (Chrome).

The whole startup process dragged out more than 15 minutes (with a distinct delay for every printer in *serverCreatePrinter*, but then the web interface on "http://raspi.local.:8000" appeared without even a need to refresh the browser window.

**Comment by KurtPfeifle** [comment]
I re-compiled after *`./configure --disable-ssl`*. This did not seem to make a difference.

**Comment by KurtPfeifle** [comment]
I changed *system.conf*:  from *`Encryption IfRequested`* to *`Encryption Never`*. No difference.

**Comment by KurtPfeifle** [comment]
My [second-last comment](https://github.com/istopwg/ippsample/issues/52#issuecomment-339668465) made me think twice... I re-checked and discovered that the even *Makefiles* were no different -- whether I had run *configure* with or without *`--disable-ssl`*.

Then I found out there were different outputs in *`config.status`*: the standard configure command had these lines:

     configure:5859: checking for libgnutls-config
     configure:5892: result: no
     configure:5957: checking for libgcrypt-config
     configure:5990: result: no

This caused me to install the *gnutls-devel* packages. Now *`ldd server/ippserver`* reports that it is linked against the *libgnutls.so.28* library (which it wasn't before).

Startup times are not a bit now. There still is a noticable pause for every call of *serverCreatePrinter*. The more printers I've configured in my *run/print* and *run/print3d* sub-directories, the longer startup takes. The last run, for a total of 6 print queues to create (1 more was skipped due to a syntax error in its *.\*conf* file), it took close to 28 minutes to complete.

If the root cause is the creation of a self-signed TLS certificate in the first run, this is definitely not re-used in the next runs.

**Comment by michaelrsweet** [comment]
OK, how about Avahi then? Since the pause is per-printer we might be waiting for Avahi to respond to the DNS-SD registrations.

FWIW, all of our Raspberry Pi testing has been with Raspbian.

**Comment by michaelrsweet** [comment]
@KurtPfeifle do you have avahi running?

**Comment by KurtPfeifle** [comment]
Yes, avahi-daemon is running. I even re-started it.

**Comment by michaelrsweet** [comment]
OK, I think I narrowed this down to all of the ippFindAttribute and ippSetAttribute calls. Optimized in master...
