### ISSUE TITLE
Please sync statements about licensing in README.md / LICENSE.md

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#54]
README.md states about the licensing of this software:

> *"The tools are provided under the terms of version 2 of the GNU General Public License and GNU Library General Public License."*

I read this short as *"LGPL-2.0 and GPL-2.0"*.

LICENSE.md lists the following:

> *"original CUPS source code [....] provided under the terms of the GNU Library General Public License ("LGPL"), Version 2. [....] new IPP Sample source code  [....] provided under the terms of the New BSD License."*

I read this short as *"LGPL-2.0 and New BSD"*.

It may be needed to put these to statements in sync in order to avoid confusion.

**Comment by michaelrsweet** [comment]
Kurt, I'll fix these up when I get some spare time.

**Comment by michaelrsweet** [comment]
These are now fixed, and use the new license (Apache v2).
