### ISSUE TITLE
`ippserver` fails two "Print-Job with {US Letter,A4} PDF, Duplex" tests with "status-message='Unsupported sides keyword value'."

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#59]
Just now I reported issue #58 where I modified the *`ipp-1.1.test`* file a bit in order to get a non-failing *"Get-Jobs Operation (requested-attributes)"* tests.

Using this modified *`ipp-1.1.test`* file I proceeded to run *`ippserver`* with duplex printing enabled (*`ippserver -2 [....]`*) and ran the IPP-1.1 test again. It now tells me it supports duplex printing here...

<pre>
[Printer IPP Default from AppImage] sides-default (keyword) one-sided
[Printer IPP Default from AppImage] sides-supported (1setOf keyword) one-sided,two-sided-long-edge,two-sided-short-edge
</pre>

...as well as here:

<pre>
[Printer IPP Default from AppImage] job-creation-attributes-supported (1setOf keyword) \
   copies,ipp-attribute-fidelity,job-account-id,job-accounting-user-id,job-name, job-password,\
   job-priority,media,media-col,multiple-document-handling,orientation-requested,print-quality,\
   sides 
</pre>

Here are the relevant IPP-1.1 test results:

<pre>
    [....]
    Print-Job with A4 PDF                                                [PASS]
    Print-Job with A4 PDF, Duplex                                        [FAIL]
        RECEIVED: 194 bytes in response
        status-code = client-error-attributes-or-values-not-supported (Unsupported sides keyword value.)
        EXPECTED: STATUS successful-ok (got client-error-attributes-or-values-not-supported)
        EXPECTED: STATUS server-error-job-canceled (got client-error-attributes-or-values-not-supported)
        status-message="Unsupported sides keyword value."
        EXPECTED: job-uri
        EXPECTED: job-id
        EXPECTED: job-state
        EXPECTED: job-state-reasons
    Print-Job with US Letter PDF                                         [PASS]
    Print-Job with US Letter PDF, Duplex                                 [FAIL]
        RECEIVED: 201 bytes in response
        status-code = client-error-attributes-or-values-not-supported (Unsupported sides keyword value.)
        EXPECTED: STATUS successful-ok (got client-error-attributes-or-values-not-supported)
        EXPECTED: STATUS server-error-job-canceled (got client-error-attributes-or-values-not-supported)
        status-message="Unsupported sides keyword value."
        EXPECTED: job-uri
        EXPECTED: job-id
        EXPECTED: job-state
        EXPECTED: job-state-reasons
    [....]
</pre>

The corresponding output of the *`ippserver -2 [....]`* process for this part of the IPP-1.1 test was this:

<pre>
[Client 1] POST /ipp/print
[Client 1] Continue
[Client 1] Request: version=1.1
[Client 1] Request: operation-id=Print-Job(0002)
[Client 1] Request: request-id=85526
[Client 1] Request: operation-attributes-tag
[Client 1] Request: attributes-charset (charset) utf-8
[Client 1] Request: attributes-natural-language (naturalLanguage) en
[Client 1] Request: printer-uri (uri) http://lenjessie2.fritz.box:8888/ipp/print
[Client 1] Request: requesting-user-name (nameWithoutLanguage) kp
[Client 1] Request: job-name (1setOf nameWithoutLanguage) A4 Test Document, Duplex
[Client 1] Request: ipp-attribute-fidelity (boolean) false
[Client 1] Request: document-name (nameWithoutLanguage) document-a4.pdf
[Client 1] Request: compression (keyword) none
[Client 1] Request: document-format (mimeMediaType) application/pdf
[Client 1] Request: job-attributes-tag
[Client 1] Request: media (keyword) iso_a4_210x297mm
[Client 1] Request: sides (keyword) two-sided-long-edge
[Client 1] Print-Job compression='none'
[Client 1] Print-Job document-format='application/pdf'
[Client 1] Print-Job client-error-attributes-or-values-not-supported (Unsupported job-name 1setOf nameWithoutLanguage value.)
[Client 1] Print-Job client-error-attributes-or-values-not-supported (Unsupported sides keyword value.)
[Client 1] Response: version=1.1
[Client 1] Response: status-code=client-error-attributes-or-values-not-supported(040b)
[Client 1] Response: request-id=85526
[Client 1] Response: operation-attributes-tag
[Client 1] Response: attributes-charset (charset) utf-8
[Client 1] Response: attributes-natural-language (naturalLanguage) en
[Client 1] Response: status-message (textWithoutLanguage) Unsupported sides keyword value.
[Client 1] Response: unsupported-attributes-tag
[Client 1] Response: job-name (1setOf nameWithoutLanguage) A4 Test Document, Duplex
[Client 1] Response: sides (keyword) two-sided-long-edge
[Client 1] OK
[Client 1] serverRespondHTTP: Sending 194 bytes of IPP response (Content-Length=194)
[Client 1] serverRespondHTTP: Sent IPP response.
[Client 1] serverRespondHTTP: Flushing write buffer.
</pre>

There is also this (additionally suspect) line to be seen, talking about *"Unsupported job-name"*:

<pre>
[Client 1] Print-Job client-error-attributes-or-values-not-supported (Unsupported job-name 1setOf nameWithoutLanguage value.)
</pre>

**Comment by michaelrsweet** [comment]
This is because of the output device vs. printer attributes issue.

**Comment by michaelrsweet** [comment]
[master 088f8fe] Fix job attribute validation (Issue #49, Issue #59)
