### ISSUE TITLE
Small typo in "ipptransform" docu

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#6]
In both, the HTML and the man page for `ipptransform`,  the name is defined as `ipptran`***`a`***`form`.

Also, the *OPTIONS* subsection dealing with `-m output/format` would be better readable, if the sentences starting with    
 `-o "name=value[...name=value]"`
 `-r resolution[,...,resolution]`
 `-s {flipped|manual-tumble|normal|rotated}`
 `-t type[,...,type]`
 `-v`   
should get their own subsections.   

---- 

BTW, both docs don't seem to be from a source file included in this repository. What is the original format? Is it Markdown, hosted somewhere else? And then converted to HTML and manpage format from that Markdown?

**Comment by michaelrsweet** [comment]
The man pages are the original (source) format, and the HTML is generated from it.

**Comment by michaelrsweet** [comment]
Looks like I was missing the ".TP 5" before many of the options, so the formatting got all jumbled up.

[master b45a53d] Fix ipptransform man page (Issue #6)
