### ISSUE TITLE
ipptool man page additions for new "--ippserver" has broken formatting

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippsample#62]
Attached is a screen shot of the current man page for ipptool. What is the correct argument to be used? The "doc/ipptool.man" file seems to have syntax errors.

<img width="949" alt="screen shot 2017-12-14 at 2 50 57 pm" src="https://user-images.githubusercontent.com/8714934/34016308-98dba6fa-e0de-11e7-9e9b-2c3cf8f9f5f2.png">

**Comment by KurtPfeifle** [comment]
This same typo is also in *doc/ipptool.html*....

**Comment by michaelrsweet** [comment]
Yeah, ipptool.html is generated from the man source... :/

**Comment by michaelrsweet** [comment]
[master 61def6e] Fix man page typos.
