### ISSUE TITLE
[Missing icon] ippserver tells clients in a `-vv` message location of icon, but it's missing

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#64]
This is in the initial *`-vv`* startup message of *`ippserver`*:   

    [Client 1] Response: printer-icons (uri) https://raspi3.fritz.box:22222/ipp/print/icon.png

However, a *`wget --no-check-certificate`* to this URI does not retrieve an icon. Also, the URIs *https://raspi3.fritz.box:22222/ipp/print/* or *https://raspi3.fritz.box:22222/ipp/print/icon.png* only show pages with a place-holder.

**Comment by michaelrsweet** [comment]
Looks like the printer resource mapping is broken when there is just a single printer. Investigating...

**Comment by michaelrsweet** [comment]
[master fc4b0d6] Fix mapping of /ipp/print/icon.png and other single-printer mappings (Issue #64)
