### ISSUE TITLE
README.txt in 'test/' subdir gives wrong instructions

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#66]
Current README.txt in sub-directory *'test/'* instructs to run *'./start-server.sh from the folder where this README.txt file resides'*.

This is wrong and does not work. Users should actually run *`./test/start-server.sh`* from one directory level higher.

Pull request PR #65 has a potential solution.

**Comment by michaelrsweet** [comment]
Closing this issue and will track the fix in PR #65. FWIW, PR's are tracked as issues as well, so there is no need to open both a PR and an issue... :)
