### ISSUE TITLE
Docu for "ippproxy" mentions "ippinfra", but no "ippinfra" in this repo

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#7]
The man- and html-help docu for `ippproxy` refer to the `ippinfra` utility in the "Description" section.

However, this repository does not contain an `ippinfra` tool...

**Comment by michaelrsweet** [comment]
Yeah, that's a holdover from the CUPS repo; it should now refer to ippserver which contains the ippinfra bits.

**Comment by michaelrsweet** [comment]
[master 63a5210] Update ippproxy man page (Issue #7)
