### ISSUE TITLE
Some lines of "ipptool --ippserver" text file are not accepted by ippserver

### ISSUE THREAD

**Issue by tillkamppeter** [istopwg/ippsample#79]
I have the HP OfficeJet Pro 8730 and have generated a text file for emulating this printer with `ippserver` via
```
ipptool -tv --ippserver ~/HP-OfficeJet-Pro-8730-ipp-attrs-ippserver.txt ipp://HP18602408C229.local:631/ipp/print get-printer-attributes-2.0.test
```
Then I have run `ippserver` using this file:
```
ippserver -a ~/HP-OfficeJet-Pro-8730-ipp-attrs-ippserver.txt testprinter
```
It kept running, but complained about this line
```
ATTR unknown printer-geo-location ""
```
after commenting out the line and starting `ippserver` again it complained about (again keeping running):
```
ATTR no-value finishings-col-database ""
```
To get free of complaints after commenting out this line I have also comment out these lines
```
ATTR no-value finishings-col-ready ""
ATTR no-value finishings-col-default ""
```
Now I can assume that the full text file, minus the 4 commented out ones, get read by `ippserver`.
There are two problems:
1. The 4 lines mentioned here should either be understood by `ippserver` or `ipptool` should generate the lines correctly so that `ippserver` understands them.
2. When `ippserver` hits a line it does not understand, it should either stop or when it continues running, read all the rest of the lines (which would result in complaints about all 4 lines).

**Comment by tillkamppeter** [comment]
Here is the file generated by the `ipptool` command from above.
[HP-OfficeJet-Pro-8730-ipp-attrs-ippserver.txt](https://github.com/istopwg/ippsample/files/1734046/HP-OfficeJet-Pro-8730-ipp-attrs-ippserver.txt)
I am using a GIT snapshot of ippsample of Feb 13, 2018.

**Comment by michaelrsweet** [comment]
Guessing this is a bug in ipptool's --ippserver output - out-of-band values don't need the third argument. Will investigate when I am back in the office on Tuesday.

**Comment by michaelrsweet** [comment]
[master 32c2739] Fix --ippserver files - out-of-band values do not have values after the name (Issue #79)
