### ISSUE TITLE
Cannot compile on Raspbian (on Raspberry Pi 3)

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippsample#9]
I tried to build ippsample on a Raspberry Pi 3 with current Raspbian installed, following the `PI.md` instructions.

The `make` stage fails with this output:

<pre>
[....]
Making all in cups...
Compiling tls.c...
In file included from tls.c:44:0:
tls-gnutls.c: In function ‘httpLoadCredentials’:
tls-gnutls.c:705:17: error: conversion to ‘int’ from ‘size_t’ may change the sign of the result [-Werror=sign-conversion]
       decoded = alloc_data - num_data;
                 ^
tls-gnutls.c: In function ‘http_gnutls_load_crl’:
tls-gnutls.c:948:14: error: conversion to ‘int’ from ‘size_t’ may change the sign of the result [-Werror=sign-conversion]
    decoded = alloc_data - num_data;
              ^
tls.c: At top level:
cc1: error: unrecognized command line option "-Wno-tautological-compare" [-Werror]
cc1: all warnings being treated as errors
../Makedefs:138: recipe for target 'tls.o' failed
make[1]: *** [tls.o] Error 1
Makefile:30: recipe for target 'all' failed
make: *** [all] Error 1
</pre>

I have the required packages installed with these versions:

<pre>
$ dpkg -l  libnss-mdns avahi-daemon avahi-utils  libavahi-client-dev libgnutls28-dev zlib1g-dev
    [....]
    ||/ Name                   Version         Architektur  Beschreibung
    +++-======================-===============-============-===================================================
    ii  avahi-daemon           0.6.31-5        armhf        Avahi mDNS/DNS-SD daemon
    ii  avahi-utils            0.6.31-5        armhf        Avahi browsing, publishing and discovery utilities
    ii  libavahi-client-dev    0.6.31-5        armhf        Development files for the Avahi client library
    ii  libgnutls28-dev:armhf  3.3.8-6+deb8u3  armhf        GNU TLS library - development files
    ii  libnss-mdns:armhf      0.10-6          armhf        NSS module for Multicast DNS name resolution
    ii  zlib1g-dev:armhf       1:1.2.8.dfsg-2  armhf        compression library - development
</pre>

**Comment by michaelrsweet** [comment]
[master 81d2ed5] Fix compile problems on Raspberry Pi (Issue #9)

**Comment by KurtPfeifle** [comment]
I get a different error now (related to MuPDF). I'll open a new issue.
